---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: 在安装 ONTAP SVM DSC 之前，可以运行此脚本来检查 SVM 中的事件速率 
keywords: event, checker, rate, sizing, cloud secure 
---
= SVM事件速率检查程序(代理规模估算指南)
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
事件速率检查器用于在安装 ONTAP SVM 数据收集器之前检查 SVM 中的 NFS/SMB 组合事件速率，以查看一个代理计算机能够监控的 SVM 数量。使用事件速率检查器作为规模估算指南、帮助您规划安全环境。

一个代理最多可支持50个数据收集器。



== 要求

* 集群IP
* 集群管理员用户名和密码



NOTE: 运行此脚本时，不应为要确定事件速率的 SVM 运行任何 ONTAP SVM 数据收集器。

步骤

. 按照 CloudSecure 中的说明安装代理。
. 安装代理后，以 sudo 用户身份运行 _server_data_rate_checker.sh_ 脚本：
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. 此脚本要求在 Linux 计算机中安装 _sshpass_ 。可通过两种方式安装它：
+
.. 运行以下命令：
+
 linux_prompt> yum install sshpass
.. 如果不起作用，请从 Web 将 _sshpass_ 下载到 Linux 计算机并运行以下命令：
+
 linux_prompt> rpm -i sshpass


. 出现提示时，请提供正确的值。请参见以下示例。
. 运行此脚本大约需要 5 分钟。
. 运行完成后，此脚本将从 SVM 中打印事件速率。您可以在控制台输出中检查每个 SVM 的事件速率：
+
 “Svm svm_rate is generating 100 events/sec”.


每个 ONTAP SVM 数据收集器都可以与一个 SVM 相关联，这意味着每个数据收集器都能够接收单个 SVM 生成的事件数量。

请记住以下几点：

a)使用此表作为一般规模估算指南。您可以增加核心和/或内存的数量来增加支持的数据收集器数量、最多可增加50个数据收集器：

|===


| 代理计算机配置 | SVM 数据收集器的数量 | Agent Machine 可以处理的最大事件速率 


| 4 核， 16 GB | 10 个数据收集器 | 每秒 20 ， 000 个事件 


| 4 核， 32 GB | 20 个数据收集器 | 每秒 20 ， 000 个事件 
|===
b ）要计算事件总数，请添加为该代理的所有 SVM 生成的事件。

c ）如果脚本未在高峰时段运行，或者流量峰值难以预测，请保留 30% 的事件速率缓冲区。

B + C 应小于 A ，否则 Agent 计算机将无法监控。

换言之，可添加到单个代理计算机的数据收集器数量应遵循以下公式：

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
有关其他前提条件和要求、请参见link:concept_cs_agent_requirements.html["代理要求"]页面。



== 示例

假设我们有三个 SVMS ，每秒生成的事件速率分别为 100 ， 200 和 300 个。

我们将应用以下公式：

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
控制台输出可在 Agent 计算机中的当前工作目录中的文件名 _fpolicy_stat_<SVM Name>.log__ 中找到。

在以下情况下，此脚本可能会提供错误的结果：

* 提供的凭据， IP 或 SVM 名称不正确。
* 如果已存在具有相同名称，序列号等的 fpolicy ，则会出现错误。
* 脚本在运行时会突然停止。


下面显示了一个脚本运行示例：

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== 故障排除

|===


| 问题 | 问题解答 


| 如果我在已配置工作负载安全性的SVM上运行此脚本、它是仅使用SVM上的现有fpolicy配置还是设置一个临时脚本并运行此过程？ | 即使已为工作负载安全性配置SVM、事件速率检查器也可以正常运行。不应产生任何影响。 


| 是否可以增加可运行此脚本的SVM数量？ | 是。只需编辑脚本并将 SVM 的最大数量从 5 更改为任何所需数量即可。 


| 如果增加SVM的数量、是否会增加脚本的运行时间？ | 不会。即使增加了SVM数量、该脚本也将运行最长5分钟。 


| 是否可以增加可运行此脚本的SVM数量？ | 是。您需要编辑脚本并将 SVM 的最大数量从 5 更改为任何所需的数量。 


| 如果增加SVM的数量、是否会增加脚本的运行时间？ | 不会。即使增加了SVM数量、该脚本也将运行最长5分钟。 


| 如果我使用现有代理运行事件速率检查程序、会发生什么情况？ | 对现有代理运行事件速率检查发生原因 程序可能会增加SVM上的延迟。这种增加在事件速率检查程序运行期间是临时的。 
|===