---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: 高级搜索技术可以帮助您找到您正在寻找的资产。 
keywords: asset page, objects, search, advanced, alerts 
---
= 搜索资产和警报的提示和技巧
:hardbreaks:
:allow-uri-read: 


[role="lead"]
可以使用多种搜索技术来搜索监控环境中的数据或对象。

* *通配符搜索*
+
您可以使用 * 字符执行多字符通配符搜索。例如，_applic*n_ 将返回 _application_。

* *搜索中使用的短语*
+
短语是一组用双引号括起来的单词；例如“VNX LUN 5”。您可以使用双引号来搜索名称或属性中包含空格的文档。

* 布尔运算符
+
使用布尔运算符 OR、AND 和 NOT，您可以组合多个术语以形成更复杂的查询。

+
或

+
OR 运算符是默认的连接运算符。

+
如果两个术语之间没有布尔运算符，则使用 OR 运算符。

+
OR 运算符链接两个术语，如果其中一个术语存在于文档中，则查找匹配的文档。

+
例如，_storage OR netapp_ 搜索包含 _storage_ 或 _netapp_ 的文档。

+
与大多数术语匹配的文档将获得高分。

+
与

+
您可以使用 AND 运算符来查找两个搜索词都存在于单个文档中的文档。例如，_storage AND netapp_ 搜索同时包含 _storage_ 和 _netapp_ 的文档。

+
您可以使用符号 *&&* 代替单词 AND。

+
不是

+
当您使用 NOT 运算符时，所有包含 NOT 之后的术语的文档都将从搜索结果中排除。例如，_storage NOT netapp_ 搜索仅包含 _storage_ 而不包含 _netapp_ 的文档。

+
您可以使用符号 *!* 代替单词 NOT。



搜索不区分大小写。



== 使用索引词搜索

与更多索引术语匹配的搜索会获得更高的分数。

搜索字符串被空格分成单独的搜索词。例如，搜索字符串“storage aurora netapp”被拆分为三个关键字：“storage”、“aurora”和“netapp”。使用所有三个术语进行搜索。与大多数这些术语匹配的文档将获得最高分数。您提供的信息越多，搜索结果就越好。例如，您可以按名称和型号搜索存储。

用户界面显示跨类别的搜索结果，每个类别显示前三个结果。如果您没有找到期望的对象，您可以在搜索字符串中包含更多术语以改进搜索结果。

下表提供了可以添加到搜索字符串的索引术语列表。

|===
| 类别 | 索引术语 


| 存储 | “存储”名称供应商型号 


| 存储池 | “storagepool”名称 存储的名称 存储的 IP 地址 存储的序列号 存储供应商 存储型号 所有关联内部卷的名称 所有关联磁盘的名称 


| 内部体积 | “internalvolume”名称 存储的名称 存储的 IP 地址 存储的序列号 存储供应商 存储型号 存储池的名称 所有关联共享的名称 所有关联应用程序的名称 


| 卷 | “卷”名称标签所有内部卷的名称存储池的名称存储的名称存储的 IP 地址存储的序列号存储供应商存储模型 


| 存储节点 | “storagenode”名称 存储的名称 存储的 IP 地址 存储的序列号 存储供应商 存储型号 


| 主机 | “主机”名称 IP 地址 所有相关应用程序的名称 


| 数据存储库 | “数据存储区”名称虚拟中心 IP 所有卷的名称所有内部卷的名称 


| 虚拟机 | “虚拟机”名称 DNS 名称 IP 地址 主机名称 主机的 IP 地址 所有数据存储区的名称 所有关联应用程序的名称 


| 开关（常规和 NPV） | “交换机” IP 地址 wwn 名称 序列号 型号 域 ID 结构名称 结构的 wwn 


| 应用程序 | “应用程序”名称 租户 业务线 业务部门 项目 


| 磁带 | “磁带” IP地址名称序列号供应商 


| 端口 | “端口”WWN 名称 


| 网络结构 | “织物” wwn 名称 


| Storage Virtual Machine (SVM) | “storagevirtualmachine”名称 UUID 
|===