---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: 使用 SVM 事件速率检查器测量 NFS/SMB 事件速率，并在部署工作负载安全数据收集器之前确定最佳代理大小。 
keywords: event, checker, rate, sizing, cloud secure 
---
= Event Rate Checker：Agent 规模调整指南
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在部署数据收集器之前，通过测量 SVM 生成的 NFS 和 SMB 事件率来确定最佳 Agent 计算机大小。Event Rate Checker 脚本可帮助您了解容量限制（每个 Agent 最多 50 个数据收集器），并确保您的 Agent 基础架构可以处理您的预期事件量以进行可靠的威胁检测。



== 要求：

* 集群 IP
* 集群管理员用户名和密码



NOTE: 运行此脚本时，不应为正在确定事件率的 SVM 运行ONTAP SVM 数据收集器。

步骤：

. 按照 CloudSecure 中的说明安装代理。
. 安装代理后，以 sudo 用户身份运行 _server_data_rate_checker.sh_ 脚本：
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. 该脚本需要在 Linux 机器上安装 _sshpass_。有两种安装方法：
+
.. 运行以下命令：
+
 linux_prompt> yum install sshpass
.. 如果这不起作用，则从网络下载 _sshpass_ 到 Linux 机器并运行以下命令：
+
 linux_prompt> rpm -i sshpass


. 出现提示时提供正确的值。请参阅下面的示例。
. 该脚本大约需要 5 分钟才能运行。
. 运行完成后，脚本将从 SVM 打印事件率。您可以在控制台输出中检查每个 SVM 的事件率：
+
 “Svm svm_rate is generating 100 events/sec”.


每个 Ontap SVM 数据收集器可以与单个 SVM 关联，这意味着每个数据收集器将能够接收单个 SVM 生成的事件数量。

请记住以下几点：

A) 使用此表作为一般尺寸指南。您可以增加核心和/或内存的数量来增加支持的数据收集器的数量，最多可增加 50 个数据收集器：

|===


| 代理机器配置 | SVM 数据收集器的数量 | 代理机器可以处理的最大事件速率 


| 4核，16GB | 10名数据收集员 | 20K 个事件/秒 


| 4核，32GB | 20名数据收集员 | 20K 个事件/秒 
|===
B) 要计算总事件数，请将该代理的所有 SVM 生成的事件数相加。

C) 如果脚本不在高峰时段运行，或者高峰流量难以预测，则保持 30% 的事件率缓冲。

B+C应该小于A，否则Agent机器会监控失败。

也就是说，单台代理机器上可以添加的数据采集器数量应遵循以下公式：

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
查看link:concept_cs_agent_requirements.html["代理要求"]页面以了解其他先决条件和要求。



== 示例

假设我们有三个 SVMS，分别每秒生成 100、200 和 300 个事件。

我们应用公式：

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
控制台输出在代理机器的当前工作目录中的文件名 __fpolicy_stat_<SVM Name>.log__ 中可用。

在以下情况下，脚本可能会给出错误的结果：

* 提供的凭据、IP 或 SVM 名称不正确。
* 具有相同名称、序列号等的已存在 fpolicy 将会出现错误。
* 脚本在运行时突然停止。


示例脚本运行如下所示：

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== 故障排除

|===


| 问题 | 问题解答 


| 如果我在已配置工作负载安全的 SVM 上运行此脚本，它是否仅使用 SVM 上现有的 fpolicy 配置，还是设置一个临时配置并运行该过程？ | 即使对于已经配置了工作负载安全性的 SVM，事件率检查器也可以正常运行。应该不会有影响。 


| 我可以增加可运行该脚本的 SVM 数量吗？ | 是只需编辑脚本并将 SVM 的最大数量从 5 更改为任何所需的数量。 


| 如果我增加 SVM 的数量，会增加脚本的运行时间吗？ | 不会。即使 SVM 的数量增加，该脚本最多也会运行 5 分钟。 


| 我可以增加可运行该脚本的 SVM 数量吗？ | 是您需要编辑脚本并将 SVM 的最大数量从 5 更改为任何所需的数量。 


| 如果我增加 SVM 的数量，会增加脚本的运行时间吗？ | 不会。即使 SVM 的数量增加，该脚本最多也会运行 5 分钟。 


| 如果我使用现有代理运行事件率检查器会发生什么情况？ | 针对已存在的代理运行事件率检查器可能会导致 SVM 上的延迟增加。当事件率检查器运行时，这种增加将是暂时的。 
|===