---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: 您可以导入推荐的仪表板来帮助回答业务洞察问题。您还可以导入之前导出的自定义仪表板。 
keywords: dashboard, gallery, import, export 
---
= 导入仪表板
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights提供了许多推荐的仪表板，为您的数据提供业务洞察。每个仪表板都包含旨在帮助回答特定问题或解决与当前在租户上收集的数据相关的特定问题的小部件。  DII 还允许您导出有用的仪表板并将其导入到另一个租户。



== 从信息板库导入

要从库导入信息板，请执行以下操作：

. 选择“可观察性”>“探索”>“所有仪表板”*
. 点击“+导入仪表板”并选择“从图库导入”。
+
根据您环境中的数据收集器，显示“推荐的仪表板”列表。仪表板可帮助解答有关不同类型对象的问题，包括 AWS、 NetApp、存储、VMware 等。

. 从列表中选择一个或多个仪表板，然后单击“添加仪表板”。这些仪表板将显示在您的仪表板列表中。


除了建议的信息板之外，您还可以选择导入与当前数据无关的 * 其他信息板 * 。例如，如果您当前未安装存储数据收集器，但计划在未来配置某些存储数据收集器，则仍可选择导入与存储相关的信息板。这些信息板可供显示，但可能无法显示任何相关数据，除非至少配置一个存储数据收集器。

具有管理员或帐户所有者角色的用户可以从信息板库导入。



== 导入已导出的仪表板

要*导出*仪表板，请在*可观察性 > 探索 > 所有仪表板*页面上，单击仪表板右侧的菜单并选择_导出_。您还可以选择多个仪表板，然后从“批量操作”下拉菜单中选择“导出”。仪表板保存在本地系统上的 .ZIP 文件中。

要*导入*仪表板，请导航到所需的租户并执行以下操作：

. 选择“可观察性”>“探索”>“所有仪表板”*
. 单击“*+导入仪表板*”并选择“从文件导入”。选择您之前导出的文件的 .ZIP。仪表板将被导入并显示在您的仪表板列表中。请注意，如果您导入的仪表板与现有仪表板同名，则仪表板名称后会附加“(2)”。

