---
sidebar: sidebar 
permalink: concept_asset_page_overview.html 
summary: 可以为大多数对象类型显示资产页面。 
keywords: asset page, objects, landing page, Virtual machine, VM, Storage Virtual Machine, SVM, Volume, Internal volume, Host, Hypervisor, pool, Storage, Datastore, Application, node, Qtree, Disk, VMDK, Port, Switch, Fabric, refresh 
---
= 资产页面概述
:hardbreaks:
:allow-uri-read: 


[role="lead"]
资产页面汇总了资产的当前状态，并包含指向有关资产及其相关资产的追加信息的链接。



== 资产页面的类型

Data Infrastructure Insight为以下资产提供了资产页面：

* 虚拟机
* Storage Virtual Machine (SVM)
* 卷
* 内部卷
* 主机（包括虚拟机管理程序）
* 存储池
* 存储
* 数据存储库
* 应用程序
* 存储节点
* qtree
* 磁盘
* VMDK
* 端口
* 交换机
* 网络结构




== 更改显示数据的时间范围

默认情况下，资产页面会显示最近 24 小时的数据；但是，您可以通过选择其他固定时间范围或自定义时间范围来更改显示的数据段，以查看较少或更多数据。

无论资产类型如何，您都可以使用每个资产页面上的选项来更改所显示数据的时间段。要更改时间范围，请单击顶部栏中显示的时间范围，然后从以下时间段中进行选择：

* 过去 15 分钟
* 过去30分钟
* 过去60分钟
* 过去 2 小时
* 过去 3 小时（这是默认值）
* 过去 6 小时
* 过去 12 小时
* 过去 24 小时
* 过去2天
* 过去3天
* 过去7天
* 过去30天
* 自定义时间范围


自定义时间范围允许您最多选择 31 个连续日期。您还可以为此范围设置开始时间和一天中的结束时间。默认开始时间为所选第一天的中午12：00、默认结束时间为所选最后一天的晚上11：59。单击应用将对资产页面应用自定义时间范围。

资产页面摘要部分以及页面上的任何表或自定义小工具中的信息会根据选定时间范围自动刷新。当前刷新率显示在"Summary (摘要)"部分的右上角以及页面上的任何相关表或小工具上。



== 添加自定义小工具

您可以将自己的小工具添加到任何资产页面。您添加的小工具将显示在该类型所有对象的资产页面上。例如，将自定义小工具添加到存储资产页面将在所有存储资产的资产页面上显示此小工具。
