---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: 资产页面的用户数据部分允许您为当前资产分配注释或应用程序。 
keywords: asset page, user data, applications, annotations 
---
= 用户数据部分
:hardbreaks:
:allow-uri-read: 


[role="lead"]
资产页面的用户数据部分显示并允许您更改任何用户定义的数据，例如应用程序和注释。



== 使用用户数据部分分配或修改应用程序

您可以将租户上运行的应用程序分配给某些资产（主机、虚拟机、卷、内部卷、qtree 和虚拟机管理程序）。用户数据部分使您能够添加、更改或删除分配给资产的应用程序。对于除卷之外的所有这些资产类型，您可以分配多个应用程序。

.步骤
. 通过执行以下任一操作来找到资产页面：
+
.. 查询资产列表，然后从列表中选择一个。
.. 在仪表板上，找到资产名称并单击它。
.. 执行搜索并从结果中选择一项资产。
+
资产页面显示。该页面的用户数据部分显示当前分配的应用程序或注释。





要更改分配的应用程序，或分配一个或多个应用程序，请下拉“应用程序”列表并选择要分配给资产的应用程序。您可以键入内容来搜索应用程序，或从列表中选择一个。

要删除应用程序，请下拉应用程序列表并取消选中该应用程序。



== 使用用户数据部分分配或修改注释

当定制Data Infrastructure Insights以跟踪公司需求的数据时，您可以定义称为注释的专门注释，并将其分配给您的资产。资产页面的用户数据部分显示分配给资产的注释，还允许您更改分配给该资产的注释。

.步骤
. 要向资产添加注释，请在资产页面的用户数据部分中单击 *+注释*。
. 从列表中选择一个注释。
. 单击“值”并根据所选注释的类型执行以下操作之一：
+
.. 如果注释类型是列表、日期或布尔值，请从列表中选择一个值。
.. 如果注释类型是文本，请输入一个值。


. 单击“Save”。


注释已分配给资产。您稍后可以使用查询按注释过滤资产。

如果要在分配注释后更改其值，请下拉注释列表并输入不同的值。

如果注释是列表类型，并且选择了“动态添加新值”选项，则除了选择现有值之外，还可以键入以添加新值。
