---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= 配置和支持的设备
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此常见问题解答解答了有关Data Infrastructure Insights配置和支持设备的常见问题。



== Data Infrastructure Insights是否会改变我的环境？

否。Data Infrastructure Insights是一个只读工具，用于收集有关您的环境的信息。Data Infrastructure Insights永远不会对您的资产或配置进行任何更改。



== Data Infrastructure Insights需要对我的设备具有什么权限级别的访问权限？

在设备支持的大多数情况下，只需要只读访问。有些解决方案不允许只读访问，因此需要适当的提升权限。



== Data Infrastructure Insights多久收集一次信息？

Data Infrastructure Insights通常每 5 分钟收集一次性能数据，每半小时发现一次逻辑和物理结构。Data Infrastructure Insights根据建议的最佳实践和可扩展性设置默认轮询间隔，但允许用户完全控制这些间隔。



== 数据基础设施洞察对我的环境有何影响？

Data Infrastructure Insights 的无代理、带外和被动 IP 通信有助于最大限度地减少设置、维护和对数据中心生态系统的影响。 Data Infrastructure Insights 的性能开发团队在监控性能本身的活动中采取了重大措施，以尽量减少对数据中心性能的影响。在正常操作环境中，影响可以忽略不计，而在利用率高或性能不佳的技术平台中，影响可以放宽或收紧。有关详细信息，请参阅Data Infrastructure Insights安装指南。



== 如何列出Data Infrastructure Insights中的所有主机/虚拟机？

数据基础设施洞察的小部件和查询列表功能可用于提供数据中心资产的库存样式列表。虚拟机列表直至主轴以及其间的众多构造都可以用于查询、小部件、仪表板和数据仓库报告，并且可以通过 RESTful API 访问。



== Data Infrastructure Insights是否为相关的非虚拟机管理程序主机（即物理服务器）提供相同类型的支持？

VMware 等虚拟机管理程序提供有关 ESXI 主机及其虚拟机 (VM) 的详细信息。对于物理服务器，Data Infrastructure Insights会收集主机 HBA 的指标。Data Infrastructure Insights采用一种独特的方法，使用正在申请专利的技术来发现物理服务器。一旦发现存储和/或交换机，物理服务器的主机名就包含在结构别名信息中。Data Infrastructure Insights选择这些主机名，在 DNS 中匹配它们，并自动将主机带入Data Infrastructure Insights。该技术极大地减少了手动输入更新和工具库存维护的需要。



== Data Infrastructure Insights是否在异构环境中提供相同的设备指标深度（奇偶校验）？

第三方平台和供应商技术的标准化、通用性和命名法程度各不相同。Data Infrastructure Insights尝试将容量和性能信息规范化到一致的框架中。一些容量和性能指标由设备计数器原生提供，例如 IOP、延迟和原始容量。当未提供计数器时，Data Infrastructure Insights可以尝试汇总值（例如，通过计算底层卷的 IOP 或容量之和），如果两者都不可用，Data Infrastructure Insights将尝试通过各种计算算法来得出指标值。Data Infrastructure Insights提供了通用的 SNMP 集成功能，以整合当前Data Infrastructure Insights尚未收集的附加指标。



== Data Infrastructure Insights是否支持光纤通道交换机？

是的，除了从您的存储资产收集数据之外， Data Infrastructure Insights还从您的租户上的Cisco、 Brocade和 QLogic 交换机获取库存和性能数据。



== 是否可以提供整个基础设施的拓扑视图？Data Infrastructure Insights是否显示“端到端可见性”？

是的，Data Infrastructure Insights动态发现并映射逻辑和物理结构，提供计算、结构、虚拟化器和后端存储的交互式端到端拓扑视图。拓扑图标允许快速启动导航到受影响的资源并有助于识别共享存储环境中的工作负载和违规行为。
