---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: 通过洞察、您可以了解资源使用情况和趋势。 
---
= 洞察力
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
通过洞察、您可以了解资源使用情况及其对其他资源的影响、或者分析时间到全满等因素。

我们提供了许多Insights。导航到*仪表板>洞察力*开始深入了解。您可以在主选项卡上查看活动的洞察力(当前正在进行的洞察力)、也可以在_INactive"洞察力_选项卡上查看非活动的洞察力。非活动洞察力是指以前处于活动状态但不再发生的洞察力。



== Insight类型



=== 共享资源面临压力

高影响工作负载会降低共享资源中其他工作负载的性能。这会使共享资源承受压力。Data Infrastructure Insight提供的工具可帮助您调查资源饱和及其对租户的影响。link:insights_shared_resources_under_stress.html["了解更多信息"]



=== Kubernetes命名空间即将用尽

通过Kubenetes命名空间即将用尽空间Insight、您可以查看Kubenetes命名空间上存在空间即将用尽风险的工作负载、并估计每个空间将达到全满前的剩余天数。link:insights_k8s_namespaces_running_out_of_space.html["了解更多信息"]



=== 回收ONTAP 冷存储

回收ONTAP冷存储Insight可提供有关ONTAP系统上卷的冷容量、潜在成本/电耗节省和建议操作项的数据。link:insights_reclaim_ontap_cold_storage.html["了解更多信息"]


NOTE: 这是一项_Preview_功能、可能会随着时间的推移进行更改。link:/concept_preview_features.html["了解更多信息。"] 关于Data Infrastructure Insight Preview功能。
