---
sidebar: sidebar 
permalink: reporting_publishing_annotations.html 
summary: 了解如何发布和取消发布注释，以便在报告中使用。 
keywords: reporting, annotations, publish, unpublish, data warehouse, dwh 
---
= 发布和取消发布报告注释
:allow-uri-read: 




== 发布和取消发布报告注释

[role="lead"]
了解如何发布注释以在报表和数据仓库中使用，以及如何在不再需要注释时正确地取消发布注释。



== 发布报告注释

在Data Infrastructure Insights中创建注释后，您可以将其发布以在报表中使用。



=== 发布注释的步骤

. 导航至“可观测性 > 丰富 > 注释”页面，然后选择“报告注释”选项卡。
. 找到要发布的注释。
. 选择注释，然后选择“发布到报表”。您还可以选择将其应用于历史数据，以便在运行历史报告时使用该注释。
. 发布后，注释即可在报告中使用。
. 注释将在下次 ETL 运行后发布，以便在报告中使用。


[NOTE]
====
任何引用该注释的报告都将使用已发布的值。如果在发布后修改了注释，则可能需要重新发布才能使这些更改在报告中生效。

====


== 取消发布报告注释

有时您可能需要删除或取消发布注释，以便它们不再用于报表。例如，某个注释可能不再需要，或者它可能包含不应出现在报告中的过时信息。



=== 取消发布注释的步骤

取消发布注释之前，请注意此操作将影响使用该注释的任何现有报告。报告可能需要编辑或专业服务协助才能删除注释参考信息。

. 在Data Infrastructure Insights用户界面中，导航至“报告注释”选项卡。
. 找到要取消发布的注释。
. 对于每个已发布注释的对象，取消选择注释并选择“保存”。
. 删除所有仍然引用该注释的查询或规则，以确保它不会被标记为“正在使用”。
. 下次 ETL 运行后，注释将被取消发布。
. ETL 完成后，如果租户端不再需要该注解，则可以将其从注解列表中删除。


[IMPORTANT]
====
注释将继续显示在数据仓库中，直到被正确取消发布为止。如果未先取消发布，直接从“注释”页面删除注释，则会留下过时的数据，这些数据可能会出现在现有报告中。请按照上述取消发布步骤操作，以确保彻底删除。

====


== 对现有报告的影响

删除或取消发布注释可能需要修改引用这些注释的现有报告。请考虑下列情形：

* 使用注释作为筛选条件或维度的报告需要进行更新。
* 如果在未更新依赖报告的情况下删除注释，则这些报告可能会返回错误或意外结果。
* 在复杂情况下，可能需要专业服务来协助进行报告修改。


建议在取消发布注释之前，先检查所有依赖于该注释的报告。
