---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: 使用报告创作工具创建自定义（“临时”）报告 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= 创建自定义报告
:hardbreaks:
:allow-uri-read: 


[role="lead"]
您可以使用报告创作工具来创建自定义报告。创建报告后，您可以保存它们并定期运行它们。报告结果可以通过电子邮件自动发送给您自己和其他人。


NOTE: 报告功能可在Data Infrastructure Insights中使用link:concept_subscribing_to_cloud_insights.html["高级版"]。

本节中的示例展示了以下过程，该过程可用于任何Data Infrastructure Insights报告数据模型：

* 确定需要通过报告回答的问题
* 确定支持结果所需的数据
* 选择报告的数据元素


在设计自定义报告之前，您需要完成一些先决任务。如果您不完成这些，报告可能会不准确或不完整。

例如，如果您没有完成设备识别过程，您的容量报告将不准确。或者，如果您没有完成注释设置（例如层级、业务部门和数据中心），您的自定义报告可能无法准确报告整个域的数据，或者可能会对某些数据点显示“N/A”。

在设计报告之前，请完成以下任务：

* 配置全部link:task_configure_data_collectors.html["数据收集者"]适当地。
* 在租户的设备和资源上输入注释（例如层、数据中心和业务部门）。在生成报告之前稳定注释是有益的，因为Data Infrastructure Insights报告会收集历史信息。




== 报告创建流程

创建自定义（也称为“临时”）报告的过程涉及几项任务：

* 规划报告的结果。
* 确定数据来支持您的结果。
* 选择包含数据的数据模型（例如，Chargeback 数据模型、Inventory 数据模型等）。
* 选择报告的数据元素。
* 可选择格式化、排序和过滤报告结果。




=== 规划自定义报告的结果

在打开报告创作工具之前，您可能需要规划希望从报告中获得的结果。使用报告创作工具，您可以轻松创建报告，并且可能不需要大量的规划；但是，从报告请求者那里了解报告要求是一个好主意。

* 确定您想要回答的确切问题。例如：
+
** 我还剩下多少容量？
** 每个业务部门的退款成本是多少？
** 各层的容量是多少，以确保业务单位在适当的存储层上保持一致？
** 我如何预测电力和冷却需求？  （通过向资源添加注释来添加自定义元数据。）


* 确定支持答案所需的数据元素。
* 确定您想要在答案中看到的数据之间的关系。不要在问题中包含不合逻辑的关系，例如“我想查看与容量相关的端口”。
* 确定数据所需的任何计算。
* 确定需要哪些类型的过滤来限制结果。
* 确定是否需要使用当前数据或历史数据。
* 确定是否需要设置报告的访问权限以将数据限制给特定受众。
* 确定报告的分发方式。例如，是否应该按照设定的时间表通过电子邮件发送或包含在团队内容文件夹区域？
* 确定谁来维护该报告。这可能会影响设计的复杂性。
* 创建报告的模型。




=== 设计报告的技巧

在设计报告时，一些技巧可能会有所帮助。

* 确定您是否需要使用当前数据或历史数据。
+
大多数报告只需要报告Data Infrastructure Insights中可用的最新数据。

* Data Infrastructure Insights报告提供有关容量和性能的历史信息，但不提供有关库存的信息。
* 每个人都可以看到所有数据；但是，您可能需要将数据限制给特定的受众。
+
为了为不同的用户细分信息，您可以创建报告并设置访问权限。





== 报告数据模型

Data Infrastructure Insights包括几个数据模型，您可以从中选择预定义的报告或创建自己的自定义报告。

每个数据模型包含一个简单数据集市和一个高级数据集市：

* 简单数据集市提供对最常用数据元素的快速访问，并且仅包含数据仓库数据的最新快照；它不包含历史数据。
* 高级数据集市提供简单数据集市的所有值和详细信息，并包括对历史数据值的访问。




=== 容量数据模型

使您能够回答有关存储容量、文件系统利用率、内部卷容量、端口容量、qtree 容量和虚拟机 (VM) 容量的问题。容量数据模型是多个容量数据模型的容器。您可以使用此数据模型创建回答各种类型问题的报告：



==== 存储和存储池容量数据模型

使您能够回答有关存储容量资源规划的问题，包括存储和存储池，并包括物理和虚拟存储池数据。这个简单的数据模型可以帮助您回答与场地容量以及按层和数据中心划分的存储池容量使用情况相关的问题。如果您对容量报告还不熟悉，那么您应该从这个数据模型开始，因为它是一个更简单、更有针对性的数据模型。您可以使用此数据模型回答类似以下的问题：

* 预计何时达到物理存储容量阈值的 80%？
* 给定层的阵列的物理存储容量是多少？
* 我的存储容量按制造商、系列和数据中心划分是多少？
* 阵列上所有层的存储利用率趋势如何？
* 我的利用率最高的 10 个存储系统有哪些？
* 存储池的存储利用率趋势如何？
* 已分配了多少容量？
* 可供分配的容量是多少？




==== 文件系统利用率数据模型

该数据模型提供了文件系统级别主机容量利用率的可见性。管理员可以确定每个文件系统的分配和使用容量，确定文件系统的类型，并按文件系统类型识别趋势统计数据。您可以使用此数据模型回答以下问题：

* 文件系统的大小是多少？
* 数据保存在哪里以及如何访问，例如本地还是 SAN？
* 文件系统容量的历史趋势如何？那么，基于此，我们可以预测未来的需求是什么？




==== 内部卷容量数据模型

使您能够回答有关内部卷已用容量、已分配容量以及一段时间内的容量使用情况的问题：

* 哪些内部卷的利用率高于预定义阈值？
* 根据趋势来看，哪些内部卷面临容量耗尽的危险？  8 我们的内部卷的已用容量与分配容量是多少？




==== 港口容量数据模型

使您能够回答有关交换机端口连接、端口状态和端口速度随时间变化的问题。您可以回答类似以下的问题，以帮助您规划购买新交换机：如何创建端口消耗预测，以预测资源（端口）可用性（根据数据中心、交换机供应商和端口速度）？

* 哪些端口可能会耗尽容量，提供数据速度、数据中心、供应商以及主机和存储端口的数量？
* 交换机端口容量随时间的变化趋势如何？
* 端口速度是多少？
* 需要什么类型的端口容量以及哪个组织即将耗尽某种端口类型或供应商？
* 购买该容量并使其可用的最佳时间是什么时候？




==== Qtree 容量数据模型

使您能够随时间推移了解 qtree 利用率趋势（使用已用容量与已分配容量等数据）。您可以按不同的维度查看信息 - 例如，按业务实体、应用程序、层级和服务级别。您可以使用此数据模型回答以下问题：

* qtree 的使用容量与每个应用程序或业务实体设置的限制相比如何？
* 我们的已使用和可用容量的趋势是什么，以便我们可以进行容量规划？
* 哪些商业实体使用的产能最多？
* 哪些应用程序消耗的容量最多？




==== 虚拟机容量数据模型

使您能够报告您的虚拟环境及其容量使用情况。该数据模型可让您报告虚拟机和数据存储的容量使用情况随时间的变化。该数据模型还提供精简配置和虚拟机退款数据。

* 如何根据为虚拟机和数据存储配置的容量确定容量分摊？
* 虚拟机未使用哪些容量，哪些未使用的部分是空闲的、孤立的或其他的？
* 从消费趋势来看我们需要购买什么？
* 通过使用存储精简配置和重复数据删除技术，我可以节省多少存储效率？


VM 容量数据模型中的容量取自虚拟磁盘 (VMDK)。这意味着使用 VM 容量数据模型的 VM 的配置大小是其虚拟磁盘的大小。这与Data Infrastructure Insights中的虚拟机视图中的预配置容量不同，后者显示的是虚拟机本身的预配置大小。



==== 卷容量数据模型

使您能够分析租户卷的各个方面，并按供应商、型号、层级、服务级别和数据中心组织数据。

您可以查看与孤立卷、未使用卷和保护卷（用于复制）相关的容量。您还可以看到不同的卷技术（iSCSI 或 FC），并将虚拟卷与非虚拟卷进行比较，以解决阵列虚拟化问题。

您可以使用此数据模型回答类似以下的问题：

* 哪些卷的利用率高于预定义的阈值？
* 我的数据中心的孤立卷容量趋势如何？
* 我的数据中心容量有多少是虚拟化的或精简配置的？
* 我的数据中心必须保留多少容量用于复制？




=== 退款数据模型

使您能够回答有关存储资源（卷、内部卷和 qtree）的已用容量和已分配容量的问题。该数据模型提供主机、应用程序和业务实体的存储容量退款和责任信息，包括当前数据和历史数据。报告数据可以按服务级别和存储层进行分类。

您可以使用此数据模型通过查找业务实体使用的容量来生成退款报告。该数据模型使您能够创建多种协议（包括 NAS、SAN、FC 和 iSCSI）的统一报告。

* 对于没有内部卷的存储，退款报告显示按卷进行的退款。
* 对于具有内部卷的存储：
+
** 如果将业务实体分配给卷，则分摊报告会按卷显示分摊情况。
** 如果业务实体未分配给卷但分配给 qtree，则分摊报告将显示按 qtree 进行的分摊。
** 如果业务实体未分配给卷且未分配给 qtree，则分摊报告将显示内部卷。
** 是否按卷、qtree 或内部卷显示费用分摊是由每个内部卷决定的，因此同一存储池中的不同内部卷可以显示不同级别的费用分摊。




容量事实会在默认时间间隔后被清除。有关详细信息，请参阅数据仓库流程。

使用 Chargeback 数据模型的报告可能与使用 Storage Capacity 数据模型的报告显示不同的值。

* 对于非NetApp存储系统的存储阵列，来自两个数据模型的数据是相同的。
* 对于NetApp和 Celerra 存储系统，Chargeback 数据模型使用单层（卷、内部卷或 qtree）来作为收费依据，而存储容量数据模型使用多层（卷和内部卷）来作为收费依据。




=== 库存数据模型

使您能够回答有关库存资源的问题，包括主机、存储系统、交换机、磁盘、磁带、qtree、配额、虚拟机和服务器以及通用设备。库存数据模型包括几个子市场，使您能够查看有关复制、FC 路径、iSCSI 路径、NFS 路径和违规的信息。库存数据模型不包括历史数据。您可以利用这些数据回答的问题

* 我拥有哪些资产？它们在哪里？
* 谁在使用这些资产？
* 我有哪些类型的设备以及这些设备的组件是什么？
* 每个操作系统有多少个主机以及这些主机上有多少个端口？
* 每个数据中心每个供应商有哪些存储阵列？
* 每个数据中心每个供应商有多少台交换机？
* 有多少端口未获得许可？
* 我们使用的是哪些供应商的磁带，每个磁带上有多少个端口？在我们开始编写报告之前，是否已经识别了所有通用设备？
* 主机和存储卷或磁带之间的路径是什么？
* 通用设备和存储卷或磁带之间的路径是什么？
* 每个数据中心每种类型的违规行为有多少次？
* 对于每个复制卷，源卷和目标卷是什么？
* 光纤通道主机 HBA 和交换机之间是否存在固件不兼容或端口速度不匹配的情况？




=== 性能数据模型

使您能够回答有关卷、应用程序卷、内部卷、交换机、应用程序、虚拟机、VMDK、ESX 与虚拟机、主机和应用程序节点的性能问题。其中许多报告是“每小时”数据、“每日”数据或两者兼有。使用此数据模型，您可以创建回答多种类型的绩效管理问题的报告：

* 在特定时间段内哪些卷或内部卷未被使用或访问？
* 我们能否查明应用程序（未使用）存储的任何潜在错误配置？
* 应用程序的整体访问行为模式是什么？
* 分层卷是否适合给定的应用程序？
* 我们能否为当前正在运行的应用程序使用更便宜的存储而不会影响应用程序性能？
* 哪些应用程序对当前配置的存储产生更多的访问？


使用交换机性能表时，您可以获得以下信息：

* 我的主机通过连接端口的流量是否均衡？
* 哪些交换机或端口出现大量错误？
* 根据端口性能，最常用的交换机有哪些？
* 根据端口性能，哪些交换机未得到充分利用？
* 基于端口性能的主机趋势吞吐量是多少？
* 指定主机、存储系统、磁带或交换机过去 X 天的性能利用率是多少？
* 哪些设备在特定交换机上产生流量（例如，哪些设备负责使用高利用率的交换机）？
* 我们的环境中特定业务部门的吞吐量是多少？


使用磁盘性能表时，您可以获得以下信息：

* 根据磁盘性能数据，指定存储池的吞吐量是多少？
* 使用率最高的存储池是什么？
* 特定存储的平均磁盘利用率是多少？
* 根据磁盘性能数据，存储系统或存储池的使用趋势如何？
* 特定存储池的磁盘使用趋势如何？


使用 VM 和 VMDK 性能表时，您可以获得以下信息：

* 我的虚拟环境是否表现最佳？
* 哪些 VMDK 报告的工作负载最高？
* 如何使用映射到不同数据存储的 VMD 报告的性能来做出有关重新分层的决策。


性能数据模型包含可帮助您确定层的适当性、应用程序的存储错误配置以及卷和内部卷的最后访问时间的信息。该数据模型提供响应时间、IOP、吞吐量、待处理写入数和访问状态等数据。



=== 存储效率数据模型

使您能够跟踪一段时间内的存储效率分数和潜力。该数据模型不仅存储了已配置容量的测量值，还存储了已使用或消耗的容量（物理测量值）。例如，当启用精简配置时，Data Infrastructure Insights指示从设备中获取了多少容量。您还可以使用此模型来确定启用重复数据删除时的效率。您可以使用存储效率数据集市来回答各种问题：

* 通过实施精简配置和重复数据删除技术，我们的存储效率节省了多少？
* 跨数据中心的存储节省是多少？
* 根据历史容量趋势，我们何时需要购买额外的存储空间？
* 如果我们启用精简配置和重复数据删除等技术，容量会有多大？
* 关于存储容量，我现在有风险吗？




=== 数据模型事实表和维度表

每个数据模型都包括事实表和维度表。

* 事实表：包含测量的数据，例如数量、原始容量和可用容量。包含维度表的外键。
* 维度表：包含有关事实的描述信息，例如数据中心和业务部门。维度是一种对数据进行分类的结构，通常由层次结构组成。维度属性有助于描述维度值。


使用不同或多个维度属性（在报告中显示为列），您可以构建访问数据模型中描述的每个维度的数据的报告。



=== 数据模型元素中使用的颜色

数据模型元素上的颜色有不同的含义。

* 黄色资产：代表测量值。
* 非黄色资产：代表属性。这些值不聚合。




=== 在一个报告中使用多个数据模型

通常，每个报告使用一个数据模型。但是，您可以编写一份包含来自多个数据模型的数据的报告。

要编写包含来自多个数据模型的数据的报告，请选择其中一个数据模型作为基础，然后编写 SQL 查询来访问来自其他数据集市的数据。您可以使用 SQL 连接功能将来自不同查询的数据组合成一个查询，以便用于编写报告。

例如，假设您想要每个存储阵列的当前容量，并且想要捕获阵列上的自定义注释。您可以使用存储容量数据模型创建报告。您可以使用当前容量和维度表中的元素，并添加单独的 SQL 查询来访问库存数据模型中的注释信息。最后，您可以使用存储名称和连接条件将库存存储数据链接到存储维度表，从而合并数据。
