---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: 使用Data Infrastructure Insights对您的数据进行预定义和自定义报告。 
keywords: reporting, cognos, data warehouse, dwh 
---
= Data Infrastructure Insights报告概述
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights报告是一种商业智能工具，可让您查看预定义的报告或创建自定义报告。


NOTE: 报告功能可在Data Infrastructure Insights中使用link:concept_subscribing_to_cloud_insights.html["高级版"]。报告功能的可用性取决于最低占用空间要求。link:https://www.netapp.com/forms/cloud-insights-contact-us/["联系您的NetApp销售代表"]了解更多信息。

通过Data Infrastructure Insights报告，您可以执行以下任务：

* 运行预定义报告
* 创建自定义报告
* 自定义报告的格式和交付方式
* 安排报告自动运行
* 电子邮件报告
* 使用颜色表示数据阈值


Data Infrastructure Insights报告可以为退款、消费分析和预测等领域生成自定义报告，并可以帮助回答以下问题：

* 我有哪些库存？
* 我的库存在哪里？
* 谁在使用我们的资产？
* 为业务部门分配的存储空间的退款是多少？
* 我多久之后才需要获得额外的存储容量？
* 业务部门是否按照适当的存储层进行排列？
* 一个月、一个季度或一年内存储分配如何变化？




== 访问Data Infrastructure Insights报告

您可以通过单击菜单中的“报告”链接来访问Data Infrastructure Insights报告。

您将进入报告界面。  Data Infrastructure Insights使用 IBM Cognos Analytics 作为其报告引擎。



== 什么是 ETL？

在处理报告时，您会听到术语“数据仓库”和“ETL”。  ETL 代表“提取、转换和加载”。  ETL 过程检索Data Infrastructure Insights中收集的数据，并将数据转换为可用于报告的格式。  “数据仓库”是指可用于报告的收集数据。

ETL 过程包括以下单独的过程：

* *提取*：从Data Infrastructure Insights获取数据。
* *转换*：将业务逻辑规则或功能应用于从Data Infrastructure Insights中提取的数据。
* *加载*：将转换后的数据保存到数据仓库以供报告使用。

