---
sidebar: sidebar 
permalink: security_information_and_region.html 
summary: Data Infrastructure Insights在整个发布生命周期中遵循安全最佳实践。 
keywords: security, risk, protection 
---
= 信息和区域
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp非常重视客户信息的安全。以下是Data Infrastructure Insights存储您的信息的方式和位置。



== Data Infrastructure Insights存储哪些信息？

Data Infrastructure Insights存储以下信息：

* 性能数据
+
性能数据是提供有关受监控设备/源性能的信息的时间序列数据。例如，这包括存储系统传送的 IO 数量、光纤通道端口的吞吐量、Web 服务器传送的页面数量、数据库的响应时间等等。

* 库存数据
+
库存数据由描述受监控设备/源及其配置方式的元数据组成。例如，这包括安装的硬件和软件版本、存储系统中的磁盘和 LUN、虚拟机的 CPU 核心、RAM 和磁盘、数据库的表空间、SAN 交换机上的端口数量和类型、目录/文件名（如果启用了存储工作负载安全性）等。

* 配置数据
+
这总结了用于管理客户库存和操作的客户提供的配置数据，例如受监控设备的主机名或 IP 地址、轮询间隔、超时值等。

* 秘密
+
机密包括Data Infrastructure Insights获取单元用于访问客户设备和服务的凭证。这些凭证使用强非对称加密进行加密，并且私钥仅存储在采集单元上，永远不会离开客户环境。由于这种设计，即使是特权Data Infrastructure InsightsSRE 也无法以纯文本形式访问客户机密。

* 功能数据
+
这是NetApp提供云数据服务时生成的数据，用于为NetApp提供云数据服务的开发、部署、运营、维护和保护信息。功能数据不包含客户信息或个人信息。

* 用户访问数据
+
允许NetApp Console与区域Data Infrastructure Insights站点通信的身份验证和访问信息，包括与用户授权相关的数据。

* 存储工作负载安全用户目录数据
+
如果启用了工作负载安全功能并且客户选择启用用户目录收集器，系统将存储从 Active Directory 收集的用户显示名称、公司电子邮件地址和其他信息。




NOTE: 用户目录数据是指工作负载安全用户目录数据收集器收集的用户目录信息，而不是Data Infrastructure Insights/工作负载安全用户本身的数据。

*没有从基础设施和服务资源收集明确的个人数据*。收集的信息仅包括性能指标、配置信息和基础设施元数据，与许多供应商电话主页非常相似，包括NetApp自动支持和 ActiveIQ。但是，根据客户的命名约定，共享、卷、虚拟机、配额树、应用程序等的数据可能包含个人身份信息。

如果启用了工作负载安全，系统还会查看 SMB 或其他共享上的文件和目录名称，其中可能包含个人身份信息。当客户启用工作负载安全用户目录收集器（其本质上是通过 Active Directory 将 Windows SID 映射到用户名）时，Data Infrastructure Insights将收集和存储显示名称、公司电子邮件地址和任何选定的附加属性。

此外，还会维护Data Infrastructure Insights的访问日志，其中包含用于登录服务的用户 IP 和电子邮件地址。



== 我的信息存储在哪里？

Data Infrastructure Insights根据您创建环境的区域存储信息。

主机区域中存储以下信息：

* 遥测和资产/对象信息，包括计数器和性能指标
* 采集单元信息
* 功能数据
* 审计Data Infrastructure Insights内部用户活动的信息
* 工作负载安全 Active Directory 信息
* 工作负载安全审计信息


无论您的Data Infrastructure Insights环境托管在哪个区域，以下信息都位于美国：

* 环境站点（有时称为“租户”）信息，例如站点/帐户所有者。
* 允许NetApp Console与区域Data Infrastructure Insights站点通信的信息，包括与用户授权有关的任何信息。
* 与Data Infrastructure Insights用户和租户之间的关系相关的信息。




=== 主办地区

主办地区包括：

* 美国：us-east-1
* 欧洲、中东和非洲地区：eu-central-1
* 亚太地区：ap-southeast-2




== 更多信息

您可以通过以下链接了解有关 NetApp 隐私和安全的更多信息：

* link:https://www.netapp.com/us/company/trust-center/index.aspx["信任中心"]
* link:https://www.netapp.com/us/company/trust-center/privacy/data-location-cross-border-transfers.aspx["跨境数据传输"]
* link:https://www.netapp.com/us/company/trust-center/privacy/bcr-binding-corporate-rules.aspx["具有约束力的公司规则"]
* link:https://www.netapp.com/us/company/trust-center/transparency/third-party-data-requests.aspx["响应第三方数据请求"]
* link:https://www.netapp.com/us/company/trust-center/privacy/privacy-principles-security-safeguards.aspx["NetApp隐私原则"]

