---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: 摘要。 
---
= 管理已配置的数据收集器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
“已安装的数据收集器”页面提供对已为Data Infrastructure Insights配置的数据收集器的访问。您可以使用此页面修改现有的数据收集器。

.步骤
. 在“Data Infrastructure Insights”菜单中，单击“可观察性”>“收集器”
+
将显示“可用数据收集器”屏幕。

. 单击*已安装的数据收集器*
+
显示所有已安装的数据收集器的列表。该列表提供收集器名称、状态、收集器正在访问的 IP 地址以及上次从设备获取数据的时间。可以在此屏幕上执行的操作包括：

+
** 控制轮询
** 更改数据收集器凭据
** 克隆数据收集器






== 控制数据收集器轮询

对数据收集器进行更改后，您可能希望它立即轮询以检查您的更改，或者您可能希望在解决问题时将数据收集器上的数据收集推迟一天、三天或五天。

.步骤
. 在“Data Infrastructure Insights”菜单中，单击“可观察性”>“收集器”
. 单击*已安装的数据收集器*
. 选中要更改的数据收集器左侧的复选框
. 单击“批量操作”并选择要采取的投票操作。
+
可以在多个数据收集器上同时执行批量操作。选择数据收集器，然后从*批量操作*菜单中选择要执行的操作。





== 编辑数据收集器信息

您可以编辑现有的数据收集器设置信息。

.要编辑单个数据收集器：
. 在Data Infrastructure Insights菜单中，单击*可观察性>收集器*以打开已安装的数据收集器列表。
. 在要修改的数据收集器右侧的选项菜单中，单击*编辑*。
+
将打开“编辑收集器”对话框。

. 输入更改并单击*测试配置*以测试新配置或单击*保存*以保存配置。


您还可以编辑多个数据收集器：

. 选中要更改的每个数据收集器左侧的复选框。
. 单击“批量操作”按钮并选择“编辑”以打开“编辑数据收集器”对话框。
. 按上述方法修改字段。
+

NOTE: 所选数据采集器必须是同一供应商和型号，并且位于同一采集单元上。

+
编辑多个数据收集器时，数据收集器名称字段显示“混合”且无法编辑。其他字段（如用户名和密码）显示“混合”并且可以编辑。在选定的数据收集器中共享相同值的字段显示当前值并且可以编辑。

+
编辑多个数据收集器时，*测试配置*按钮不可用。





== 克隆数据收集器

使用克隆功能，您可以快速添加具有与另一个数据源相同的凭据和属性的数据源。克隆允许您轻松配置同一设备类型的多个实例。

.步骤
. 在Data Infrastructure Insights菜单中，单击*可观察性>收集器*。
. 单击*已安装的数据收集器*。
. 单击要复制的数据收集器左侧的复选框。
. 在所选数据收集器右侧的选项菜单中，单击*克隆*。
+
将显示“克隆数据收集器”对话框。

. 在必填字段中输入新信息。
. 单击“保存”。


.完成后
克隆操作复制所有其他属性和设置以创建新的数据收集器。



== 对数据收集器执行批量操作

您可以同时为多个数据收集器编辑一些信息。此功能允许您在多个数据收集器上发起轮询、推迟轮询和恢复轮询。此外，您还可以删除多个数据收集器。

.步骤
. 在“Data Infrastructure Insights”菜单中，单击“可观察性”>“收集器”
. 单击*已安装的数据收集器*
. 单击要修改的数据收集器左侧的复选框。
. 在右侧的选项菜单中，单击您想要执行的选项。


.完成后
您选择的操作在数据收集器上执行。当您选择删除数据收集器时，将显示一个对话框，要求您确认该操作。
