---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: 配置NetApp SolidFire数据收集器 
keywords: data collector, queries, create 
---
= NetApp SolidFire全闪存阵列数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp SolidFire全闪存阵列数据收集器支持从 iSCSI 和光纤通道SolidFire配置进行库存和性能收集。

SolidFire数据收集器利用SolidFire REST API。数据收集器所在的采集单元需要能够启动与SolidFire集群管理 IP 地址上的 TCP 端口 443 的 HTTPS 连接。数据收集器需要能够在SolidFire集群上进行 REST API 查询的凭证。



== Terminology

Data Infrastructure Insights从NetApp SolidFire All-Flash 阵列数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 驱动器 | 磁盘 


| 集群 | 存储 


| 节点 | 存储节点 


| 卷 | 卷 


| 光纤通道端口 | 端口 


| 卷访问组、LUN 分配 | 体积图 


| iSCSI 会话 | 体积遮罩 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

以下是配置此数据收集器的要求：

* 管理虚拟 IP 地址
* 只读用户名和凭据
* 端口 443




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| 管理虚拟 IP 地址 (MVIP) | SolidFire集群的管理虚拟 IP 地址 


| 用户名 | 用于登录SolidFire集群的名称 


| 密码 | 用于登录SolidFire集群的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 连接类型 | 选择连接类型 


| 通信端口 | 用于NetApp API 的端口 


| 库存轮询间隔（分钟） | 默认为 20 分钟 


| 性能轮询间隔（秒） | 默认值为 300 秒 
|===


== 故障排除

当SolidFire报告错误时，它会在Data Infrastructure Insights中显示如下：

_尝试检索数据时收到来自SolidFire设备的错误消息。调用的是 <method> (<parameterString> )。设备发出的错误消息是（检查设备手册）：<message>_

其中：

* <method> 是一种 HTTP 方法，例如 GET 或 PUT。
* <parameterString> 是 REST 调用中包含的参数的逗号分隔列表。
* <message> 是设备返回的错误消息。


关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
