---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 配置 HP Enterprise Alletra 6000（以前称为 Nimble）数据收集器。 
---
= HPE Alletra 6000 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
HP Enterprise Alletra 6000（以前称为 Nimble）数据收集器支持 Alletra 6000 存储阵列的库存和性能数据。



== Terminology

Data Infrastructure Insights从此收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 大批 | 存储 


| 磁盘 | 磁盘 


| 卷 | 卷 


| 池 | 存储池 


| 启动程序 | 存储主机别名 


| 控制器 | 存储节点 


| 光纤通道接口 | 控制器 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

您必须具备以下条件才能从存储阵列收集库存和配置数据：

* 必须安装并配置阵列，并且可以通过其完全限定域名 (FQDN) 或阵列管理 IP 地址从客户端访问。
* 阵列必须运行 NimbleOS 2.3.x 或更高版本。
* 您必须拥有有效的用户名和密码才能进入阵列并至少具有“操作员”级别的角色。  “来宾”角色没有足够的访问权限来了解启动器配置。
* 阵列上必须打开端口 5392。


您必须具备以下条件才能从存储阵列收集性能数据：

* 阵列必须运行 NimbleOS 4.0.0 或更高版本
* 阵列必须配置卷。  NimbleOS 唯一的性能 API 是针对卷的，并且任何统计Data Infrastructure Insights报告都来自卷的统计数据




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| 阵列管理 IP 地址 | 完全限定域名 (FQDN) 或阵列管理 IP 地址。 


| 用户名 | 阵列的用户名 


| 密码 | 阵列的密码 
|===


== 高级配置

|===


| 字段 | 描述 


| 端口 | Nimble REST API 使用的端口。默认值为 5392。 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认时间间隔为 60 分钟。 
|===
注意：默认性能轮询间隔为 300 秒，无法更改。这是 HPE Alletra 6000 支持的唯一间隔。
