---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: 配置 IBM Cleversafe 数据收集器。 
---
= IBM Cleverssafe 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insight使用此数据收集器来发现IBM Cleversafe存储系统的清单和性能数据。


NOTE: IBM Cleversafe按不同的原始TB到受管单元速率进行计量。每40 TB未格式化的IBM Cleversafe容量就会被充电为1link:concept_subscribing_to_cloud_insights.html#pricing["受管单元（ MU ）"]。



== 术语

Data Infrastructure Insight从IBM Cleversafe数据收集器采集以下清单信息。对于Data Infrastructure Insight采集的每种资产类型、显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | 数据基础架构洞察力一词 


| 存储池 | 存储池 


| 容器 | 内部卷 


| 容器 | 文件共享 


| NFS共享 | 共享 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



== 要求

* 集群的外部数据服务 IP 地址
* 管理员用户名和密码
* 端口 9440




== 配置

[cols="2*"]
|===
| 字段 | 说明 


| 管理器 IP 或主机名 | 管理节点的 IP 地址或主机名 


| 用户名 | 具有超级用户或系统管理员角色的用户帐户的用户名 


| 密码 | 具有超级用户或系统管理员角色的用户帐户的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。 


| HTTP 连接超时（秒） | HTTP 超时（以秒为单位）。 
|===


== 故障排除

有关此Data Collector的其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
