---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: 配置NetApp StorageGRID数据收集器 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRID数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp StorageGRID数据收集器支持从StorageGRID配置收集库存和性能。

[NOTE]
====
为了在所有StorageGRID系统中对 DII 权利进行一致的计量，无论底层硬件拓扑和配置如何， Data Infrastructure Insights都会使用总可用容量（storagegrid_storage_utilization_total_space_bytes），而不是基于物理磁盘布局的 RAW 容量。

对于使用基于容量的许可模式的客户， StorageGRID被计量为“对象”存储。

对于使用传统 (MU) 许可模式的客户， StorageGRID按 40TiB 比 1 MU 的比率计量为二级存储。

====


== Terminology

Data Infrastructure Insights从NetApp StorageGRID收集器获取以下库存信息。对于所获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| StorageGRID | 存储 


| 节点 | 节点 


| Tenant（租户） | 存储池 


| 桶 | 内部体积 
|===


== 要求

配置此数据源的要求如下：

* StorageGRID主机 IP 地址
* 已分配“指标查询”和“租户访问”角色的用户的用户名和密码
* 端口 443




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| StorageGRID主机 IP 地址 | StorageGRID设备的管理虚拟 IP 地址 


| 用户名 | 用于登录StorageGRID设备的名称 


| 密码 | 用于登录StorageGRID设备的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 默认为 60 分钟 


| 性能轮询间隔（秒） | 默认值为 900 秒 
|===


== 单点登录（SSO）

这link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]固件版本有相应的API版本；3.0 API及更新版本支持单点登录（SSO）。

|===


| 固件版本 | API 版本 | 支持单点登录（SSO） 


| 11.1 | 2 | 否 


| 11.2 | 3.0 | 是 


| 11.5 | 3.3 | 是 
|===


== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
