---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: 配置 ECS 数据收集器。 
---
= 配置 EMC ECS 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
该数据收集器从 EMC ECS 存储系统获取库存和性能数据。对于配置，数据收集器需要 ECS 集群的 IP 地址或主机名以及用户名和密码。


NOTE: Dell EMC ECS 按照不同的原始 TB 与托管单位费率进行计量。每 40TB 未格式化 ECS 容量按 1link:concept_subscribing_to_cloud_insights.html#pricing["管理单元（MU）"] 。



== Terminology

Data Infrastructure Insights从 ECS 数据收集器获取以下库存信息。对于所获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 集群 | 存储 


| Tenant（租户） | 存储池 


| 桶 | 内部体积 


| 磁盘 | 磁盘 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

* ECS 集群的 IP 地址或主机名
* ECS 系统的用户名和密码
* 端口 4443 (HTTPS)。需要与 ECS 系统上的 TCP 端口 4443 建立出站连接。




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| ECS 主机 | ECS 系统的 IP 地址或完全限定域名 


| ECS 主机端口 | 与 ECS 主机通信使用的端口 


| ECS 用户 ID | ECS 的用户 ID 


| 密码 | ECS使用的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 默认值为 360 分钟。 
|===


== 故障排除

如果您在使用此数据收集器时遇到问题，请尝试以下操作：



=== 清单

[cols="2*"]
|===
| 问题： | 尝试一下： 


| 错误：用户身份验证失败。 | 确保您对此设备的凭证正确无误。 
|===


=== 性能

[cols="2*"]
|===
| 问题： | 尝试一下： 


| 错误：未收集足够的数据。 | * 检查日志文件中的收集时间戳并相应地修改轮询间隔 * 等待更长时间 


| 错误：性能轮询间隔太大。 | 检查日志文件 ${logfile} 中的收集时间戳并相应地修改轮询间隔 
|===
更多信息可从link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
