---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: 配置 Microsoft Hyper-V 数据收集器。 
---
= Microsoft Hyper-V 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Microsoft Hyper-V 数据收集器从虚拟化服务器计算环境获取库存和性能数据。该数据收集器可以发现独立的 Hyper-V 主机或整个集群 - 每个独立主机或集群创建一个收集器。



== Terminology

Data Infrastructure Insights从 Microsoft Hyper-V (WMI) 获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 虚拟硬盘 | 虚拟磁盘 


| 主机 | 主机 


| 虚拟机 | 虚拟机 


| 集群共享卷（CSV）、分区卷 | 数据存储 


| 互联网 SCSI 设备，多路径 SCSI LUN | LUN 


| 光纤通道端口 | 端口 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

配置此数据收集器需要以下内容：

* Hyper-V 需要打开端口 5985 以进行数据收集和远程访问/管理。
* 集群或独立虚拟机管理程序的 IP 地址或 FQDN。与将收集器指向集群中某个特定节点相比，使用浮动集群主机名或 IP 可能是最可靠的方法。
* 可在集群中的所有虚拟机管理程序上运行的管理级用户帐户。
* WinRM 需要在所有虚拟机管理程序上启用并监听
* 端口要求：通过 WMI 和动态 TCP 端口分配的端口 135 对于 Windows 2003 及更早版本为 1024-65535，对于 Windows 2008 为 49152-65535。
* DNS 解析必须成功，即使数据收集器仅指向 IP 地址
* 每个 Hyper-V 虚拟机管理程序必须为每个主机上的每个 VM 启用“资源计量”。这使得每个虚拟机管理程序可以为每个客户机上的Data Infrastructure Insights提供更多数据。如果未设置，则每个客户获取的性能指标会更少。有关资源计量的更多信息，请参阅 Microsoft 文档：
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Hyper-V 资源计量概述"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["启用-VMResourceMetering"]




NOTE: Hyper-V 数据收集器需要 Windows 采集单元。



== 配置

[cols="2*"]
|===
| 字段 | 描述 


| 群集 IP 地址或浮动群集 FQDN | 集群或独立非集群虚拟机管理程序的 IP 地址或完全限定域名 


| 用户名 | 虚拟机管理程序的管理员用户名 


| 密码 | 虚拟机管理程序的密码 


| DNS 域后缀 | 与简单主机名相结合以呈现虚拟机管理程序的 FQDN 的主机名后缀 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 默认值为 20 分钟。 
|===


== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
