---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: 配置 IBM PowerVM 数据收集器。 
---
= 配置 IBM PowerVM 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
IBM PowerVM (SSH) 数据收集器用于收集由硬件管理控制台 (HMC) 管理的 IBM POWER 硬件实例上运行的虚拟分区的信息。



== Terminology

Data Infrastructure Insights从 IBM POWER 硬件实例上运行的虚拟分区获取库存信息。对于所获取的每种资产类型，都会显示该资产最常用的术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 硬盘 | 虚拟磁盘 


| 管理系统 | 主机 


| LPAR、VIO 服务器 | 虚拟机 


| 卷组 | 数据存储 


| 物理体积 | LUN 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

配置和使用此数据收集器必须满足以下要求：

* 硬件管理控制台 (HMC) 的 IP 地址
* 通过 SSH 访问硬件管理控制台 (HMC) 的用户名和密码
* 端口要求 SSH-22
* 所有管理系统和逻辑分区安全域的查看权限
+
用户还必须具有查看 HMC 配置的权限以及收集 HMC 控制台安全分组的 VPD 信息的能力。还必须允许用户在逻辑分区安全组下访问虚拟 IO 服务器命令。最佳做法是从操作员的角色开始，然后删除所有角色。  HMC 上的只读用户没有在 AIX 主机上运行代理命令的权限。

* IBM 的最佳实践是让两个或多个 HMC 监控设备。请注意，这可能会导致OnCommand Insight报告重复的设备，因此强烈建议将冗余设备添加到此数据收集器的高级配置中的“排除设备”列表中。




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| 硬件管理控制台 (HMC) IP 地址 | PowerVM 硬件管理控制台的 IP 地址或完全限定域名 


| HMC 用户 | 硬件管理控制台的用户名 


| 密码 | 用于硬件管理控制台的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认值为 20 分钟。 


| SSH 端口 | 用于 SSH 到 PowerVM 的端口 


| 密码 | 用于硬件管理控制台的密码 


| 重试次数 | 库存重试次数 


| 排除设备 | 要排除的设备 ID 或显示名称的逗号分隔列表 
|===


== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
