---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: '配置 HDS NAS (HNAS) 数据收集器。' 
---
= 配置 Hitachi Vantara NAS 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Hitachi Vantara NAS 数据收集器是一种库存和配置数据收集器，支持发现 HDS NAS 集群。Data Infrastructure Insights支持发现 NFS 和 CIFS 共享、文件系统（内部卷）和跨度（存储池）。



== Terminology

Data Infrastructure Insights从 HNAS 数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 层级 | 磁盘组 


| 集群 | 存储 


| 节点 | 存储节点 


| 跨度 | 存储池 


| 系统驱动器 | 后端 Lun 


| 文件系统 | 内部体积 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

* 设备 IP 地址
* 端口 22，SSH 协议
* 用户名和密码 - 权限级别：主管
* 注意：此数据收集器基于 SSH，因此托管它的 AU 必须能够在 HNAS 本身或集群连接到的系统管理单元 (SMU) 上启动到 TCP 22 的 SSH 会话。




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| HNAS 主机 | HNAS 管理主机的 IP 地址或完全限定域名 


| 用户名 | HNAS CLI 的用户名 


| 密码 | 用于 HNAS CLI 的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认值为 30 分钟。 
|===


== 故障排除

如果您在使用此数据收集器时遇到问题，请尝试以下操作：



=== 清单

[cols="2*"]
|===
| 问题： | 尝试一下： 


| “连接错误”，错误消息为“设置 shell 通道错误：”或“打开 shell 通道错误” | 可能是由于网络连接问题或 SSH 配置错误造成的。确认与备用 SSH 客户端的连接 


| “超时”或“检索数据时出错”，错误消息为“命令：XXX 已超时。” | * 使用备用 SSH 客户端尝试该命令 * 增加超时 


| “连接错误”或“登录凭据无效”，错误消息为“无法与设备通信：” | * 检查 IP 地址 * 检查用户名和密码 * 确认与备用 SSH 客户端的连接 
|===
更多信息可从link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
