---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: 设备分辨率可帮助您准确跟踪环境中的性能和库存。 
---
= 设备解析规则
:hardbreaks:
:allow-uri-read: 


[role="lead"]
您可以创建设备解析规则来识别Data Infrastructure Insights当前无法自动识别的主机、存储和磁带。您创建的规则可以识别当前环境中的设备，还可以识别添加到环境中的类似设备。



== 创建设备解析规则

创建规则时，首先要确定规则所针对的信息源、用于提取信息的方法以及是否将 DNS 查找应用于规则的结果。

[cols="2*"]
|===


| 用于识别设备的来源 | * 主机的 SRM 别名 * 包含嵌入式主机或磁带名称的存储别名 * 包含嵌入式主机或磁带名称的交换机别名 * 包含嵌入式主机名的区域名称 


| 用于从源中提取设备名称的方法 | * 按原样（从 SRM 中提取名称）* 分隔符* 正则表达式 


| DNS 查找 | 指定是否使用 DNS 来验证主机名 
|===
您可以在“自动解决规则”选项卡中创建规则。以下步骤描述了规则创建过程。

.操作步骤
. 单击“管理”>“设备分辨率”
. 在“自动解析规则”选项卡中，单击“+ 主机规则”或“+ 磁带规则”。
+
显示“*解决规则*”屏幕。

+

NOTE: 单击“查看匹配条件”链接可获取有关创建正则表达式的帮助和示例。

. 在*类型*列表中选择您想要识别的设备。
+
您可以选择_Host_或_Tape_。

. 在“*来源*”列表中，选择要用于识别主机的来源。
+
根据您选择的来源，Data Infrastructure Insights将显示以下响应：

+
.. *Zones* 列出了Data Infrastructure Insights需要识别的区域和 WWN。
.. *SRM* 列出了需要由Data Infrastructure Insights识别的未识别别名
.. *存储别名*列出了需要由Data Infrastructure Insights识别的存储别名和 WWN
.. *交换机别名*列出了需要由Data Infrastructure Insights识别的交换机别名


. 在*方法*列表中选择您想要用来识别主机的方法。
+
|===


| 源 | 方法 


| SRM | 原样，分隔符，正则表达式 


| 存储别名 | 分隔符、正则表达式 


| 切换别名 | 分隔符、正则表达式 


| 区域 | 分隔符、正则表达式 
|===
+
** 使用分隔符的规则需要分隔符和主机名的最小长度。主机名的最小长度是Data Infrastructure Insights应该用来识别主机的字符数。Data Infrastructure Insights仅对这么长或更长的主机名执行 DNS 查找。
+
对于使用分隔符的规则，输入字符串由分隔符标记，并通过对相邻标记进行几种组合来创建主机名候选列表。然后对列表进行排序，从大到小。例如，对于 _vipsnq03_hba3_emc3_12ep0_ 的输入链，列表将产生以下内容：

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emc3
*** hba3


** 使用正则表达式的规则需要正则表达式、格式和区分大小写选择。


. 单击“*运行 AR*”以运行所有规则，或单击按钮中的向下箭头以运行您创建的规则（以及自上次完整运行 AR 以来创建的任何其他规则）。
+
规则运行的结果显示在*FC 识别*选项卡中。





== 启动自动设备分辨率更新

设备分辨率更新提交自上次全自动设备分辨率运行以来添加的手动更改。运行更新可用于提交和运行对设备分辨率配置所做的新手动输入。没有执行完整的设备解析运行。

.操作步骤
. 登录Data Infrastructure InsightsWeb UI。
. 单击“管理”>“设备分辨率”
. 在*设备分辨率*屏幕中，单击*运行 AR*按钮中的向下箭头。
. 单击“*更新*”开始更新。




== 规则辅助人工识别

此功能用于特殊情况，即您想要运行特定规则或规则列表（有或没有一次性重新排序）来解析未知主机、存储和磁带设备。

.开始之前
您有许多尚未识别的设备，并且还有多条成功识别其他设备的规则。


NOTE: 如果您的源仅包含部分主机或设备名称，请使用正则表达式规则并格式化它以添加缺失的文本。

.操作步骤
. 登录Data Infrastructure InsightsWeb UI。
. 单击“管理”>“设备分辨率”
. 单击“*光纤通道识别*”选项卡。
+
系统显示设备及其解析状态。

. 选择多个未识别的设备。
. 单击*批量操作*并选择*设置主机分辨率*或*设置磁带分辨率*。
+
系统显示识别屏幕，其中包含成功识别设备的所有规则的列表。

. 将规则的顺序更改为满足您需求的顺序。
+
规则的顺序在识别屏幕中发生了改变，但没有全局改变。

. 选择满足您需求的方法。


Data Infrastructure Insights按照方法出现的顺序执行主机解析过程，从顶部开始。

当遇到适用的规则时，规则名称会显示在规则列中并标识为手动。

有关的：link:task_device_resolution_fibre_channel.html["光纤通道设备解析"] link:task_device_resolution_ip.html["IP设备解析"] link:task_device_resolution_preferences.html["设置设备分辨率首选项"]
