---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: 配置 DELL EMC ScaleIO/PowerFlex 数据收集器。 
---
= DELL EMC ScaleIO/PowerFlex 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
ScaleIO/PowerFlex 数据收集器从 ScaleIO 和 PowerFlex 存储收集库存信息。为了进行配置，此数据收集器需要 ScaleIO/PowerFlex 网关地址以及管理员用户名和密码。



== Terminology

Data Infrastructure Insights从 ScaleIO/PowerFlex 数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| MDM（元数据管理器）集群 | 存储 


| SDS（ScaleIO/PowerFlex 数据服务器） | 存储节点 


| 存储池 | 存储池 


| 卷 | 卷 


| 设备 | 磁盘 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

* 对管理员用户帐户的只读访问权限
* 端口要求：HTTPS 端口 443




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| ScaleIO/PowerFlex 网关 | ScaleIO/PowerFlex 网关的 IP 地址或 FQDN，以逗号 (,) 或分号 (;) 分隔 


| 用户名 | 用于登录 ScaleIO/PowerFlex 设备的管理员用户名 


| 密码 | 用于登录 ScaleIO/PowerFlex 设备的密码 
|===


== 高级配置

单击“库存”复选框以启用库存收集。

[cols="2*"]
|===
| 字段 | 描述 


| HTTPS 端口 | 443 


| 库存轮询间隔（分钟） | 默认值为 60。 


| 连接超时（秒） | 默认值为 60。 
|===


== 故障排除

更多信息可从link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
