---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: 配置 HDS 数据收集器。 
---
= 日立 HCP 数据采集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
该数据收集器使用 HCP 管理 API 支持日立内容平台 (HCP)。


NOTE: 日立内容平台按照不同的原始 TB 与托管单位费率进行计量。每 40 TB 未格式化的 HCP 容量按 1link:concept_subscribing_to_cloud_insights.html#pricing["管理单元（MU）"] 。



== Terminology

Data Infrastructure Insights从 Hitachi HCP 数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| HCP集群 | 存储 


| Tenant（租户） | 存储池 


|  | 命名空间 


| 内部体积 | 节点 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 库存需求

为了收集库存数据，您必须具备以下条件：

* HCP服务器的IP地址
* HCP 软件的只读用户名和密码以及同行权限




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| HCP 主机 | HCP 主机的 IP 地址或完全限定域名 


| HCP 端口 | 默认值为 9090 


| HCP 用户 ID | HCP 主机的用户名。 


| HCP 密码 | 用于 HCP 主机的密码。 


| HCP 认证类型 | 选择 HCP_LOCAL 或 ACTIVE_DIRECTORY 
|===


== 高级配置

|===


| 字段 | 描述 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认值为 60。 


| 性能轮询间隔（秒） | 性能轮询之间的间隔。默认值为 900。 
|===
更多信息可从link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
