---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: 如何创建注释。 
---
= 使用注释
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您创建注释并将其分配给您监控的资产。注释是提供有关资产信息的说明，例如物理位置、使用寿命、存储层或卷服务级别。



== 定义注释

使用注释，您可以向资产添加符合您的业务需求的自定义业务特定数据。虽然Data Infrastructure Insights提供了一组默认注释，例如资产生命周期（生日或寿命终止）、建筑物或数据中心位置和层级，但您可能会发现您想以其他方式查看数据。

自定义注释中的数据补充了已经收集的设备数据，例如交换机制造商、端口数量和性能统计数据。您使用注释添加的数据不会被Data Infrastructure Insights发现。

.开始之前
* 列出必须与环境数据关联的任何行业术语。
* 列出必须与环境数据关联的公司术语。
* 确定您可能使用的任何默认注释类型。
* 确定您需要创建哪些自定义注释。您需要先创建注释，然后才能将其分配给资产。


使用以下步骤创建注释。

.步骤
. 在Data Infrastructure Insights菜单中，单击“可观察性”>“丰富”>“注释”
. 单击“*+ 注释*”创建新注释。
. 输入新注释的名称、描述和类型。
+
例如，输入以下内容来创建定义数据中心 4 中资产的物理位置的文本注释：

+
** 输入注释的名称，例如“位置”
** 输入注释内容的描述，例如“物理位置是数据中心 4”
** 输入注释的“类型”，例如“文本”。






== 手动为资产分配注释

为资产分配注释可以帮助您以与您的业务相关的方式对资产进行排序、分组和报告。虽然您可以使用注释规则自动将注释分配给特定类型的资产，但您可以使用资产页面将注释分配给单个资产。

.开始之前
* 您必须已经创建了要分配的注释。


.步骤
. 登录到您的Data Infrastructure Insights环境。
. 找到要应用注释的资产。
+
** 您可以通过查询、从仪表板小部件中选择或搜索来定位资产。找到所需的资产后，单击链接即可打开该资产的登录页面。


. 在资产页面的用户数据部分中，单击 *+ 注释*。
. 将显示“添加注释”对话框。
. 从列表中选择一个注释。
. 单击“值”并根据所选注释的类型执行以下操作之一：
+
** 如果注释类型是列表、日期或布尔值，请从列表中选择一个值。
** 如果注释类型是文本，请输入一个值。


. 单击“保存”。


如果在分配注释后想要更改其值，请单击注释字段并选择其他值。如果注释是列表类型，并且选择了“动态添加新值”选项，则除了选择现有值之外，还可以键入新值。



== 使用注释规则分配注释

要根据您定义的标准自动将注释分配给资产，请配置注释规则。Data Infrastructure Insights根据这些规则将注释分配给资产。  Data Infrastructure Insights还提供了两个默认注释规则，您可以根据需要修改它们，如果不想使用它们，则可以删除它们。



=== 创建注释规则

作为手动将注释应用于单个资产的替代方法，您可以使用注释规则自动将注释应用于多个资产。当 Insight 评估注释规则时，在单个资产页面上手动设置的注释优先于基于规则的注释。

.开始之前
您必须已经为注释规则创建了查询。

.关于此任务
虽然您可以在创建规则时编辑注释类型，但您应该提前定义类型。

.步骤
. 单击“管理”>“注释规则”
+
注释规则页面显示现有注释规则的列表。

. 单击“*+ 添加*”。
. 执行以下操作：
+
.. 在“*名称*”框中，输入描述规则的唯一名称。
+
该名称将出现在注释规则页面中。

.. 单击“*查询*”并选择用于将注释应用于资产的查询。
.. 单击*注释*并选择要应用的注释。
.. 单击“*值*”并为注释选择一个值。
+
例如，如果您选择生日作为注释，则您可以为该值指定一个日期。

.. 点击“保存”
.. 如果您想立即运行所有规则，请单击“运行所有规则”；否则，规则将按照定期安排的时间间隔运行。



