---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: 使用查询为对象分配多个应用程序或标注，或者从对象中删除多个应用程序或标注。 
keywords: query, queries, application, annotation, multiple 
---
= 为资产分配多个应用程序或从资产中删除多个应用程序
:hardbreaks:
:allow-uri-read: 


[role="lead"]
您可以使用查询为资产分配多个应用程序或从资产中删除多个link:task_create_application.html["应用程序"]应用程序、而不必手动分配或删除这些应用程序。


NOTE: 您可以使用这些步骤以相同方式添加或删除link:task_defining_annotations.html["标注"]。

.开始之前
您必须已创建一个查询，用于查找要编辑的所有资产。

.步骤
. 单击*浏览*并选择*度量查询*。
+
此时将显示 "Queries" 页面。

. 单击用于查找资产的查询的名称。
+
此时将显示与查询关联的资产列表。

. 在列表中选择所需资产，或者单击顶部复选框以选中全部。
+
此时将显示"批量操作"下拉列表。

. 要将应用程序添加到选定资产，请单击批量操作，然后选择*Add Application*。
. 选择一个或多个应用程序。
+
您可以为主机，内部卷， qtree 和虚拟机选择多个应用程序；但是， 您只能为一个卷或共享选择一个应用程序。

. 单击 * 保存 * 。
. 要删除分配给资产的应用程序，请单击批量操作并选择*Remove Application*。
. 选择要删除的一个或多个应用程序。
. 单击 * 删除 * 。


您分配的任何新应用程序将覆盖资产上从其他资产派生的任何应用程序。例如，卷会继承主机中的应用程序，而在将新应用程序分配给卷时，新应用程序会优先于派生应用程序。

在批量添加操作上单击_Save_或在批量删除操作上单击_Remove_后、Data Infrastructure Insight会通知您该操作需要一段时间。您可以取消此消息；此操作将在后台继续。


NOTE: 对于具有大量相关资产的环境，向这些资产继承应用程序分配可能需要几分钟的时间。如果您拥有许多相关资产，请留出更多时间进行继承。
