---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: 您可以创建注释规则来自动将注释应用于多个资产。 
keywords: annotate, annotation, rules 
---
= 创建注释规则
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用注释规则根据您定义的标准自动将注释应用于多个资产。Data Infrastructure Insights根据这些规则将注释分配给资产。当 Cloud Insight 评估注释规则时，在单个资产页面上手动设置的注释优先于基于规则的注释。

.开始之前
您必须已经为注释规则创建了查询。

.步骤
. 在Data Infrastructure Insights菜单中单击*管理>注释规则*。
. 单击“*+ 规则*”添加新的注释规则。
+
将显示“添加规则”对话框。

. 执行以下操作：
+
.. 在“*名称*”框中，输入描述规则的唯一名称。
+
该名称出现在注释规则页面中。

.. 单击“查询”并选择Data Infrastructure Insights用来识别注释适用的资产的查询。
.. 单击*注释*并选择要应用的注释。
.. 单击“*值*”并为注释选择一个值。
+
例如，如果您选择生日作为注释，则您可以为该值指定一个日期。

.. 点击“保存”
.. 如果您想立即运行所有规则，请单击“运行所有规则”；否则，规则将按照定期安排的时间间隔运行。
+

NOTE: 在大型Data Infrastructure Insights环境中，您可能会注意到运行注释规则似乎需要一段时间才能完成。这是因为索引器首先运行，并且必须在运行规则之前完成。索引器使Data Infrastructure Insights能够搜索或过滤数据中的新对象或更新的对象和计数器。规则引擎等待索引器完成更新后再应用规则。







== 修改注释规则

您可以修改注释规则以更改规则的名称、注释、注释的值或与规则关联的查询。

.步骤
. 在Data Infrastructure Insights菜单中，单击*管理>注释规则*。
+
注释规则页面显示现有注释规则的列表。

. 找到您想要修改的注释规则。
+
您可以通过在过滤框中输入值来过滤注释规则，或者单击页码按页浏览注释规则。

. 单击要修改的规则的菜单图标。
. 点击“编辑”
+
将显示“编辑规则”对话框。

. 修改注释规则的名称、注释、值或查询。




== 更改规则顺序

注释规则从规则列表的顶部到底部进行处理。要更改规则的处理顺序，请执行以下操作：

.步骤
. 单击要移动的规则的菜单图标。
. 根据需要单击*上移*或*下移*，直到规则出现在您想要的位置。


请注意，当运行多个规则来更新资产上的相同注释时，第一个规则（从上到下运行）应用注释并更新资产，然后第二个规则应用但不会更改前一个规则已经设置的任何注释。



== 删除注释规则

您可能想要删除不再使用的注释规则。

.步骤
. 在Data Infrastructure Insights菜单中，单击*管理>注释规则*。
+
注释规则页面显示现有注释规则的列表。

. 找到要删除的注释规则。
+
您可以通过在过滤框中输入值来过滤注释规则，或者单击页码按页浏览注释规则。

. 单击要删除的规则的菜单图标。
. 点击“删除”
+
系统弹出确认信息，询问您是否要删除该规则。

. 单击“确定”

