---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: 注册Data Infrastructure Insights并创建您的租户。 
keywords: onboarding, new user 
---
= Data Infrastructure Insights入职
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在开始使用Data Infrastructure Insights之前，您必须在 * NetApp Console* 门户上注册。如果您已经拥有NetApp Console登录名，则只需几个简单的步骤即可开始免费试用Data Infrastructure Insights。



== 创建您的NetApp Console帐户

要开始使用 NetApp 的云服务，请访问link:https://console.netapp.com/["* NetApp Console*"^]然后点击*开始*。

* 如果您尚未注册，请选择“注册”
* 输入有效的企业电子邮件地址并选择密码。
* 输入您的公司名称和您的全名。
* 接受条款和条件并选择*继续*。
* 控制台将引导您完成入门步骤。




=== 如果我已经拥有NetApp Console登录信息该怎么办？

拥有NetApp Console帐户后，只需选择link:https://console.netapp.com/["* NetApp Console*"^]门户页面。

输入您的电子邮件地址和密码。然后您将进入 NetApp 的云产品页面。

导航至*分析和控制>可观察性*以了解Data Infrastructure Insights和/或请求演示。



== 开始您的Data Infrastructure Insights免费试用

如果您是第一次登录Data Infrastructure Insights，请阅读有关Data Infrastructure Insights所能提供的一切信息，当您_准备好开始使用_时，点击*申请试用*并填写您的信息。

作为试用租户设置的一部分，您将选择托管租户的区域，以及您希望将租户部署在 AWS 还是 Azure 上。

租户创建完成后，使用控制台凭据登录并开始免费试用 30 天Data Infrastructure Insights。在此试用期间，您可以探索Data Infrastructure Insights所提供的功能。

在免费试用期间，您可以link:concept_subscribing_to_cloud_insights.html["开始订阅"]随时了解Data Infrastructure Insights。当您订阅后，您可以根据当前订阅使用Data Infrastructure Insights功能。



== Sign in并前往

租户创建完成后，您可以随时登录NetApp BlueXP Portal 并导航至以下位置： link:https://services.cloud.netapp.com["云服务"] 页面并选择“转到Data Infrastructure Insights”。

您还可以直接打开浏览器访问Data Infrastructure Insights租户 URL，例如：

 \https://<tenant-prefix>.c01.cloudinsights.netapp.com/
该 URL 还将包含在每个用户的邀请电子邮件中，以便于访问和添加书签。如果用户尚未登录控制台，系统将提示他们登录。


NOTE: 新用户仍必须注册访问控制台，然后才能访问其租户 URL。

首次登录新租户时，系统将引导您完成设置link:task_getting_started_with_cloud_insights.html["*开始收集数据*"]。



== 注销

要退出Data Infrastructure Insights，请单击您的*用户名*并选择*注销*。您将返回到控制台登录屏幕。


NOTE: 注销Data Infrastructure Insights将使您退出控制台。您还将退出使用控制台登录的其他NetApp云服务。



=== 非活动超时

默认情况下，如果六小时（360 分钟）内没有任何活动，控制台将注销用户。无论活动如何，用户将在七天后被注销。
