---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: 配置 Dell EMC RecoverPoint 数据收集器。 
---
= Dell EMC RecoverPoint 数据收集器
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
EMC RecoverPoint 数据收集器的主要使用情形是，发现 RecoverPoint 存储设备所促进的卷到卷复制关系。此收集器还会发现 Recoverpoint 设备本身。请注意， Dell/EMC 销售适用于 VM 的 VMware 备份解决方案 — "RecoverPoint for VMs" —此收集器不支持此功能

在配置方面，数据收集器需要存储处理器的 IP 地址以及只读用户名和密码。

EMC RecoverPoint 数据收集器收集 RecoverPoint 在其他存储阵列之间协调的卷到卷复制关系。Data Infrastructure Insight会显示每个RecoverPoint集群的存储阵列、并收集该集群上节点和存储端口的清单数据。不会收集任何存储池或卷数据。



== 要求

要配置此数据收集器，需要以下信息：

* 存储处理器的 IP 地址或完全限定域名
* 只读用户名和密码
* 通过端口 443 进行 REST API 访问




== 配置

[cols="2*"]
|===
| 字段 | 说明 


| RecoverPoint 的地址 | RecoverPoint 集群的 IP 地址或完全限定域名 


| 用户名 | RecoverPoint 集群的用户名 


| 密码 | RecoverPoint 集群使用的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| TCP端口 | 用于连接到 Recoverpoint 集群的 TCP 端口 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。默认值为20分钟。 


| 排除的集群 | 要在轮询时排除的集群 ID 或名称的逗号分隔列表。 
|===


== 故障排除

有关此Data Collector的其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
