---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: 使用查询为对象分配多个应用程序或注释，或者从对象中删除多个应用程序或注释。 
keywords: query, queries, application, annotation, multiple 
---
= 将多个应用程序分配给资产或从资产中删除多个应用程序
:hardbreaks:
:allow-uri-read: 


[role="lead"]
您可以分配多个link:task_create_application.html["应用程序"]使用查询从资产中添加或删除多个应用程序，而不必手动分配或删除它们。


NOTE: 您可以按照以下步骤添加或删除link:task_defining_annotations.html["标注"]以同样的方式。

.开始之前
您必须已经创建了一个查询来查找您要编辑的所有资产。

.步骤
. 单击“*探索*”并选择“*指标查询*”。
+
显示查询页面。

. 单击查找资产的查询的名称。
+
显示与查询相关的资产列表。

. 在列表中选择所需的资产或单击顶部复选框选择全部。
+
显示批量操作下拉菜单。

. 要将应用程序添加到选定的资产，请单击“批量操作”并选择“添加应用程序”。
. 选择一个或多个应用程序。
+
您可以为主机、内部卷、qtree 和虚拟机选择多个应用程序；但是，您只能为一个卷或共享选择一个应用程序。

. 单击“保存”。
. 要删除分配给资产的应用程序，请单击“批量操作”并选择“*删除应用程序*”。
. 选择要删除的一个或多个应用程序。
. 单击“*删除*”。


您分配的任何新应用程序都会覆盖该资产上从其他资产派生的任何应用程序。例如，卷从主机继承应用程序，当新应用程序分配给卷时，新应用程序优先于派生的应用程序。

在批量添加操作中单击“保存”或在批量删除操作中单击“删除”后，Data Infrastructure Insights会通知您该操作将需要一些时间。您可以忽略此消息；操作将在后台继续。


NOTE: 对于具有大量相关资产的环境，将应用程序分配继承到这些资产可能需要几分钟。如果您拥有许多相关资产，请留出更多时间进行继承。
