---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: 配置 Oracle ZFS 数据收集器。 
---
= Oracle ZFS Storage Appliance 数据收集器
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insight使用Oracle ZFS存储设备数据收集器收集清单和性能数据。



== 术语

Data Infrastructure Insight使用Oracle ZFS数据收集器采集清单信息。对于Data Infrastructure Insight采集的每种资产类型、显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | 数据基础架构洞察力一词 


| 磁盘(SSD) | 磁盘 


| 集群 | 存储 


| 控制器 | 存储节点 


| LUN | 卷 


| LUN 映射 | 卷映射 


| 启动程序，目标 | 卷掩码 


| 共享 | 内部卷 
|===
注意：这些只是常见的术语映射，可能并不代表此数据源的所有情形。



== 要求

* ZFS Controller-1 和 ZFS Controller-2 的主机名
* 管理员用户名和密码
* 端口要求： 215 HTTP/HTTPS




== 所需性能指标

Oracle ZFS设备使存储管理员可以灵活地捕获性能统计信息。Data Infrastructure Insight希望您在高可用性对中配置_each_控制器、以捕获以下指标：

* SMB2.ops[共享]
* nfs3.ops[共享]
* NFS4.ops[共享]
* NFS4-1.ops[共享]


如果控制器未能捕获任何或所有这些数据、则可能会导致Data Infrastructure Insight不存在或低估"内部卷"上的工作负载。



== 配置

[cols="2*"]
|===
| 字段 | 说明 


| ZFS Controller-1 主机名 | 存储控制器 1 的主机名 


| ZFS Controller-2 主机名 | 存储控制器 2 的主机名 


| 用户名 | 存储系统管理员用户帐户的用户名 


| 密码 | 管理员用户帐户的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| 连接类型 | HTTPS 或 HTTP 也会显示默认端口 


| 覆盖连接端口 | 如果为空，请使用连接类型字段中的默认端口，否则输入要使用的连接端口 


| 清单轮询间隔 | 默认值为60秒 


| 性能轮询间隔（秒） | 默认值为300。 
|===


== 故障排除

如果此数据收集器出现问题，请尝试执行以下操作：



=== 清单

[cols="2a, 2a"]
|===
| 问题： | 请尝试以下操作： 


 a| 
" 登录凭据无效 "
 a| 
验证 ZFS 用户帐户和密码



 a| 
" 配置错误 " ，并显示错误消息 "REST Service is disabled"
 a| 
验证是否已在此设备上启用 REST 服务。



 a| 
" 配置错误 " ，并显示错误消息 " 用户未授权命令 "
 a| 
此错误可能是由于配置的用户未包含某些角色(例如、"advanced_Analytics ")。

对具有只读角色的用户应用分析范围可能会删除此错误。请按照以下步骤操作：

. 在ZFS系统上，从“Configuration -> Users”(配置->用户)屏幕中，将鼠标移动到角色上并双击以进行编辑
. 从范围下拉菜单中选择"分析"。此时将显示可能属性的列表。
. 单击最顶部的复选框、它将选择所有三个属性。
. 单击右侧的添加按钮。
. 单击弹出窗口右上角的应用按钮。此时将关闭弹出窗口。


|===
有关其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
