---
sidebar: sidebar 
permalink: task_dc_redhat_openshift_virtualization.html 
keywords: data collector, Red Hat OpenShift Virtualization 
summary: 配置 Red Hat OpenShift Virtualization 数据收集器。 
---
= Red Hat OpenShift 虚拟化数据收集器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DII Red Hat OpenShift 虚拟化收集器将尝试发现在 OpenShift 虚拟化环境中运行的 OSV 计算工作负载 - 此收集器不会发现所有 OpenShift pod。这是一个基于 HTTPS REST API 的收集器。建议为每个 OSV 集群创建一个收集器。

此收集器的身份验证方法是绑定到服务帐户的身份验证令牌。要同时创建用户帐户和令牌：

....
oc create sa acq-readonly-cluster-user -n default
oc adm policy add-cluster-role-to-user cluster-reader -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-user-binding
oc adm policy add-cluster-role-to-user cluster-monitoring-view -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-monitor-user-binding
....
运行这 3 个命令并注意是否存在任何错误。

命令完成后：

 oc sa new-token acq-readonly-cluster-user
此操作将创建绑定到您的用户的令牌。

最后，您可能还希望 OSV 管理员运行：

 oc cluster-info
这将返回用于管理的主机名/IP 地址。每个 DII OSV 收集器都需要指向用于 OSV 管理的 IP/主机名。



== Terminology

对于Data Infrastructure Insights获取的每种资产类型，都会显示该资产最常用的术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 磁盘 | 虚拟磁盘 


| 主机 | 主机 


| 虚拟机 | 虚拟机 


| 存储域 | 数据存储 


| 逻辑单元 | LUN 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

* 通过 REST API 在端口 443 上访问 Red Hat OpenShift Virtualization 服务器的 IP 地址
* 只读用户名和密码
* RHEV 版本 3.0+




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| RHEV 服务器 IP 地址 | 存储系统的IP地址 


| 用户名 | 具有管理员权限的用户名 


| 管理员特权帐户的密码 | 密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| HTTPS 通信端口 | 用于与 RHOV 进行 HTTPS 通信的端口 


| 库存轮询间隔（分钟） | 默认值为 20 分钟。 
|===


== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
