---
sidebar: sidebar 
permalink: task_config_cs_incloud.html 
keywords: Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet,  cloud secure 
summary: 为Cloud Volumes ONTAP和Amazon FSx for NetApp ONTAP设置工作负载安全数据收集器，以监控文件访问、用户活动并检测整个云存储基础架构中的威胁。 
---
= 配置Cloud Volumes ONTAP和Amazon FSx for NetApp ONTAP收集器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
通过为Cloud Volumes ONTAP和Amazon FSx for NetApp ONTAP配置 Workload Security 数据收集器，监控整个云存储基础架构中的文件和用户访问。本指南提供了在 AWS 中部署代理并将其连接到云存储实例的分步说明。



== Cloud Volumes ONTAP存储配置

请参阅OnCommand Cloud Volumes ONTAP文档，以配置单节点/HA AWS 实例来托管工作负载安全代理：https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[]

配置完成后，按照以下步骤设置您的 SVM：https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html[]



== 支持的平台

* Cloud Volumes ONTAP，在所有可用的云服务提供商处均受支持。例如：Amazon、Azure、Google Cloud。
* ONTAPAmazon FSx




== 代理机器配置

代理机器必须在云服务提供商的各自子网中配置。在[代理要求]中阅读有关网络访问的更多信息。

以下是在 AWS 中安装代理的步骤。可以在 Azure 或 Google Cloud 中按照适用于云服务提供商的等效步骤进行安装。

在 AWS 中，使用以下步骤将机器配置为用作工作负载安全代理：

使用以下步骤将机器配置为工作负载安全代理：

.步骤
. 登录 AWS 控制台并导航到 EC2-Instances 页面并选择_启动实例_。
. 选择具有此页面中提到的适当版本的 RHEL 或 CentOS AMI：https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html[]
. 选择 Cloud ONTAP实例所在的 VPC 和子网。
. 选择 _t2.xlarge_（4 vcpus 和 16 GB RAM）作为分配的资源。
+
.. 创建 EC2 实例。


. 使用 YUM 包管理器安装所需的 Linux 包：
+
.. 安装 _wget_ 和 _unzip_ 本机 Linux 包。






== 安装工作负载安全代理

. 以管理员或帐户所有者的身份登录到您的Data Infrastructure Insights环境。
. 导航到工作负载安全*收集器*并单击*代理*选项卡。
. 单击 *+Agent* 并指定 RHEL 作为目标平台。
. 复制代理安装命令。
. 将代理安装命令粘贴到您登录的 RHEL EC2 实例中。这将安装 Workload Security 代理，提供所有link:concept_cs_agent_requirements.html["代理先决条件"]均已满足。


有关详细步骤，请参阅此链接： https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent



== 故障排除

下表描述了已知问题及其解决方法。

|===


| 问题 | 解决方法 


| 数据收集器显示“工作负载安全：无法确定 Amazon FxSN 数据收集器的ONTAP类型”错误。客户无法将新的 Amazon FSxN 数据收集器添加到 Workload Security 中。从代理到端口 443 上的 FSxN 集群的连接超时。防火墙和 AWS 安全组已启用所需规则以允许通信。代理已部署并且也位于同一个 AWS 账户中。同一代理用于连接和监控其余的NetApp设备（并且所有设备都在运行）。 | 通过将 fsxadmin LIF 网络段添加到代理的安全规则来解决此问题。如果您不确定端口，请允许所有端口。 
|===