---
sidebar: sidebar 
permalink: task_dc_na_ontap_rest.html 
keywords: data collector, ontap, ontap, CDOT, REST 
summary: ONTAP REST数据收集器 
---
= NetApp ONTAP REST数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此数据收集器使用REST API调用从运行ONTAP 9.14.1及更高版本的存储系统采集清单、EMS日志和性能数据。对于早期版本的ONTAP系统、请使用基于ZAPI的NetApp ONTAP数据管理软件收集器类型。


NOTE: ONTAP REST收集器可用于替代以前基于ONTAPI的收集器。因此、收集或报告的指标可能存在差异。有关ONTAPI和REST之间差异的详细信息、请参见link:https://docs.netapp.com/us-en/ontap-restmap-9141/index.html["ONTAP 9.14.1 ONTAPI到REST的映射"]文档。



== 要求

配置和使用此数据收集器的要求如下：

* 您必须能够访问具有所需访问级别的用户帐户。请注意、创建新的REST用户/角色时需要管理员权限。
+
** 从功能上讲、数据基础架构洞察力主要发出读取请求、但要向ONTAP阵列注册、需要一些写入权限。请参见下面的_关于权限的注意事项_。


* ONTAP 9.14.1或更高版本。
* 端口要求：443




== 有关权限的注释

由于许多数据基础架构洞察的ONTAP信息板都依赖于高级ONTAP计数器、因此您应在数据收集器高级配置部分中保持启用*启用高级计数器数据收集*状态。

要在集群级别为数据基础架构洞察力创建本地帐户、请使用集群管理管理员用户名/密码登录到ONTAP、然后在ONTAP服务器上执行以下命令：

. 开始之前，您必须使用 _Administrator_ 帐户登录到 ONTAP ，并且必须启用 _diagnostic-level commands_。
. 检索类型为_admin_的Vserver的名称。您将在后续命令中使用此名称。
+
 vserver show -type admin
. 使用以下命令创建角色：
+
....
security login rest-role create -role {role name} -api /api -access readonly
security login rest-role create -role {role name} -api /api/cluster/agents -access all
vserver services web access create -name spi -role {role name} -vserver {vserver name as retrieved above}
security login create -user-or-group-name {username} -application http -authentication-method password -role {role name}
....
. 使用以下命令创建只读用户。执行 create 命令后，系统将提示您输入此用户的密码。
+
 security login create -username ci_user -application http -authentication-method password -role ci_readonly


如果使用 AD/LDAP 帐户，则命令应为

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application http -authentication-method domain -role ci_readonly
生成的角色和用户登录信息如下所示。实际输出可能会有所不同：

[listing]
----
security login rest-role show -vserver <vserver name> -role restRole

               Role                                    Access
Vserver        Name            API                     Level
----------     -------------   -------------------     ------
<vserver name> restRole        /api                    readonly
                               /api/cluster/agents     all
2 entries were displayed.

security login show -vserver <vserver name> -user-or-group-name restUser

Vserver: <vserver name>
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
restUser       http        password      restRole         no     none
----


== 迁移

要从先前的ONTAP (ontapi)数据收集器迁移到新的ONTAP REST收集器、请执行以下操作：

. 添加REST收集器。建议输入的用户信息与为上一个收集器配置的用户不同。例如、使用上面权限部分中记下的用户。
. 暂停上一个收集器、使其不再继续收集数据。
. 让新的REST收集器采集数据至少30分钟。忽略在此期间不显示为"正常"的任何数据。
. 休息期过后、随着REST收集器继续采集数据、您应该会看到数据保持稳定。


如果需要、您可以使用相同的过程返回到上一个收集器。



== 配置

[cols="2*"]
|===
| 字段 | 说明 


| ONTAP管理IP地址 | NetApp集群的IP地址或完全限定域名。必须为集群管理IP/FQDN。 


| ONTAP REST用户名 | NetApp 集群的用户名 


| ONTAP REST密码 | NetApp 集群的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| 清单轮询间隔（分钟） | 默认值为 60 分钟。 


| 性能轮询间隔（秒） | 默认值为60秒。 


| 高级计数器数据收集 | 选择此选项可在轮询中包含 ONTAP 高级计数器数据。默认情况下处于启用状态。 


| 启用EMS事件收集 | 选择此选项可包括ONTAP EMS日志事件数据。默认情况下处于启用状态。 


| EMS轮询间隔(秒) | 默认值为60秒。 
|===


== 术语

数据基础架构洞察从ONTAP数据收集器采集清单、日志和性能数据。对于所采集的每种资产类型，都会显示该资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | 数据基础架构洞察力一词 


| 磁盘 | 磁盘 


| RAID 组 | 磁盘组 


| 集群 | 存储 


| 节点 | 存储节点 


| 聚合 | 存储池 


| LUN | 卷 


| 卷 | 内部卷 


| Storage Virtual Machine/Vserver | Storage Virtual Machine 
|===


== ONTAP 数据管理术语

以下术语适用于您在 ONTAP 数据管理存储资产登录页面上可能找到的对象或参考。其中许多术语也适用于其他数据收集器。



=== 存储

* 型号—此集群中唯一的离散节点型号名称的逗号分隔列表。如果集群中的所有节点的型号类型相同，则只会显示一个型号名称。
* Vendor —与配置新数据源时看到的 Vendor 名称相同。
* Serial Number—阵列UUID
* IP —通常是数据源中配置的 IP 或主机名。
* 微代码版本—固件。
* 原始容量—系统中所有物理磁盘的基本 2 总和，而不管其角色如何。
* 延迟—表示主机在读取和写入工作负载方面所遇到的情况。理想情况下、Data Infrastructure Insight会直接获取这种价值、但事实往往并非如此。Data Infrastructure Insight通常会根据各个内部卷的统计信息执行IOPS加权计算、而不是使用阵列来提供此功能。
* 吞吐量—从内部卷聚合。管理—可能包含设备管理界面的超链接。由Data Infrastructure Insight数据源以编程方式在清单报告中创建。




=== 存储池

* 存储—此池所在的存储阵列。必填。
* type —从枚举的可能性列表中获取的描述性值。最常见的是 " 聚合 " 或 "RAID 组 " 。
* 节点—如果此存储阵列的架构使池属于特定存储节点，则其名称将在此处显示为指向其自身登录页面的超链接。
* 使用 Flash Pool —是 / 否值—此基于 SATA/SAS 的池是否使用 SSD 进行缓存加速？
* 冗余— RAID 级别或保护方案。RAID-DP 为双奇偶校验， raid_TP 为三重奇偶校验。
* 容量—此处的值为逻辑已用容量，可用容量和逻辑总容量以及这些容量中使用的百分比。
* 过量使用的容量—如果您使用效率技术分配的卷或内部卷总容量大于存储池的逻辑容量，则此处的百分比值将大于 0% 。
* Snapshot —已用快照容量和总容量，前提是存储池架构将部分容量专用于专为快照划分的区域。MetroCluster 配置中的 ONTAP 很可能会显示这一点，而其他 ONTAP 配置则不会显示这一点。
* 利用率—一个百分比值，显示为该存储池贡献容量的任何磁盘的最高磁盘繁忙百分比。磁盘利用率不一定与阵列性能密切相关—如果没有主机驱动的工作负载，则由于磁盘重建，重复数据删除活动等，利用率可能会很高。此外，许多阵列的复制实施可能会提高磁盘利用率，而不会显示为内部卷或卷工作负载。
* IOPS —为该存储池贡献容量的所有磁盘的 IOPS 之和。吞吐量—为该存储池贡献容量的所有磁盘的总吞吐量。




=== 存储节点

* 存储—此节点所属的存储阵列。必填。
* HA 配对节点—在某个节点将故障转移到一个且只有另一个节点的平台上，通常会显示在此处。
* 状态—节点的运行状况。仅当阵列运行状况良好，足以供数据源进行资源清点时才可用。
* model —节点的型号名称。
* version —设备的版本名称。
* Serial Number —节点序列号。
* 内存—如果可用，则为基础 2 内存。
* 利用率—在 ONTAP 上，这是一个来自专有算法的控制器压力指数。每次性能轮询都会报告一个介于 0 到 100% 之间的数字，该数字在 WAFL 磁盘争用或平均 CPU 利用率中较高。如果您观察到持续值 > 50% ，则表示规模估算不足—可能是控制器 / 节点不够大或旋转磁盘不足，无法承受写入工作负载。
* IOPS—直接源自节点对象上的ONTAP REST调用。
* 延迟—直接源自节点对象上的ONTAP REST调用。
* 吞吐量—直接源自节点对象上的ONTAP REST调用。
* 处理器— CPU 计数。




== ONTAP功率指标

多个ONTAP模型为数据基础架构洞察力提供了功率指标、可用于监控或发出警报。下面列出的受支持和不受支持的型号并不全面、但应提供一些指导；一般来说、如果型号与列表中的型号属于同一系列、则支持应相同。

支持的型号：

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

不支持的型号：

FAS2620 AFF FAS3250 FAS3270 FAS500f FAS6280 FAS/FAS8020 FAS或AFF FAS 8040 FAS或AFF 8060 FAS或AFF 8080



== 故障排除

如果此数据收集器出现问题，请尝试执行以下操作：

[cols="2*"]
|===
| 问题： | 请尝试以下操作： 


| 尝试创建ONTAP REST数据收集器时、会出现如下错误：配置：10.193.70.14：10.193.70.14上的ONTAP REST API不可用：10.193.70.14无法获取/API/cluster：400错误请求 | 这可能是由于older ONTAP阵列(例如ONTAP 9.6)没有REST API功能。ONTAP 9.14.1是ONTAP REST收集器支持的最低ONTAP版本。在REST之前的ONTAP版本中、应该会收到"400 Bad Request"响应。对于支持REST但为9.14.1 9.10.1或更高版本的ONTAP版本、您可能会看到以下simillar消息：Configuration：10.193.98.84：ONTAP REST API位于10.193.98.84不可用：10.193.98.84：ONTAP REST API位于10.193.98.84：cheryl5-cluster-api a3cb3247-3d3c-11ee-8ff3-009.56b364a7、但其版本不是最低版本14.1。 


| 我看到ONTAP ontapi收集器显示数据的指标为空或"0"。 | ONTAP REST不会报告仅在ONTAP系统内部使用的指标。例如、ONTAP REST不会收集系统聚合、只会收集类型为"数据"的SVM。可能报告零数据或空数据的其他ONTAP REST指标示例：内部卷：REST不再报告vol0。聚合：REST不再报告aggr0。存储：大多数指标都是内部卷指标的汇总、将受上述指标的影响。Storage Virtual Machine：REST不再报告类型为"数据"以外的SVM (例如、"集群"、"GMT"、"节点")。由于默认性能轮询周期从15分钟更改为5分钟、您可能还会注意到具有数据的图形的外观发生变化。轮询频率越高、意味着要绘制的数据点就越多。 
|===
有关其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
