---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: 当查询高 I/O 密度时，您想要排除根卷。 
keywords: NetApp, root volume, high I/O, 
---
= 确保 IO 密度报告仅描述内部数据量
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp根卷包含用于管理存储系统的目录和配置文件。当查询高 I/O 密度时，您需要排除这些根卷。

当监控您的环境时，更重要的是确定哪些内部数据卷产生高 I/O 密度数字。为了准确地识别数据卷，您需要将NetApp内部卷与用于监控 I/O 密度的查询隔离。

本指南介绍如何轻松识别NetApp根聚合、将其与内部卷查询的结果隔离，以及创建在将任何新的NetApp根聚合添加到系统时将其排除的规则。以下 Insight 功能用于确保您的 I/O 密度报告来自内部数据卷：

* 创建一个查询来识别 Insight 监控的所有NetApp根聚合。
* 每个NetApp根聚合都分配有一个注释。
* 创建注释规则以将注释应用于新的NetApp根聚合。


本指南中的步骤也可应用于其他供应商的存储系统。您需要识别包含用于管理存储系统的目录和配置文件的卷，并使用类似的步骤排除这些卷。



== 创建查询以识别NetApp根聚合

查询根据用户选择的条件提供细粒度的搜索。使用查询，您可以搜索租户中包含NetApp根聚合的内部卷。

.步骤
. 创建查询以识别租户上的NetApp根聚合：单击 *查询 > 新建查询 > 选择资源类型*（？）
. 单击“存储池”
. 输入根聚合的名称
+
此示例使用“aggr0”作为名称。创建聚合时，只需遵循以下名称要求：

+
.. 它必须以字母或下划线 (_) 开头。
.. 它只能包含字母、数字和下划线。
.. 其长度不得超过 250 个字符。在大多数情况下，聚合的名称是 aggr0、aggr_0 或类似的名称。可能需要一个迭代过程来识别租户上的所有NetApp根聚合。


. 单击“*保存*”并输入新查询的名称。
+
如前所述，这可能是一个迭代过程，需要多个查询才能识别所有NetApp根聚合。





== 为查询返回的根卷创建注释

注释是您分配给资产的专门注释，允许您通过注释过滤资产。您创建的注释将用于识别租户上的NetApp根聚合，并确保它们不包含在特定报告中。

.开始之前
您必须已确定要从“高 I/O 密度”报告中排除的所有根聚合。

.步骤
. 在“Data Infrastructure Insights”菜单中，单击“管理”>“注释”
. 点击“添加”
+
.. 输入注释的名称：*RootAggr*
.. 输入注释的描述：*从“高 I/O 密度”报告中删除根聚合*
.. 输入注释类型：*布尔值*


. 点击“保存”




== 创建注释规则以自动从 I/O 密度报告中排除特定聚合

作为手动将注释应用于单个资产的替代方法，您可以使用注释规则自动将注释应用于多个资产。注释规则基于您创建的查询，当在系统上运行时，它们会将新资产添加到现有资产集中。当这些资产集从报告中排除时，新资产也会自动被排除。

.开始之前
您必须已创建并保存一个查询，该查询可识别您在租户上识别的NetApp根聚合。

.步骤
. 在Data Infrastructure Insights工具栏中，单击*管理>注释规则*。
. 单击“*添加*”。将显示“添加规则”对话框。
+
.. 在名称框中，输入描述规则的唯一名称：*“RootAggrExclude”*
.. 单击查询并选择 Insight 应该用来应用注释规则的查询：*“Aggregate0”*
.. 单击注释并选择：“Root agg exclude”
.. 单击“值”并输入“True”



