---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: 配置 Nutanix 数据收集器。 
---
= Nutanix NX 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights使用 Nutanix 数据收集器来发现 Nutanix NX 存储系统的库存和性能数据。



== Terminology

Data Infrastructure Insights从 Nutanix 数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 存储池 | 存储池 


| Nutanix容器 | 内部体积 


| Nutanix容器 | 文件共享 


| NFS 共享 | 共享 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

* 集群的外部数据服务 IP 地址
* 只读用户名和密码，除非正在使用 volume_groups，在这种情况下，需要管理员用户名和密码
* 端口要求：HTTPS 443




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| Prism 外部 IP 地址 | 集群的外部数据服务 IP 地址 


| 用户名 | 管理员帐户的用户名 


| 密码 | 管理员帐户的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| TCP 端口 | 用于连接 Nutanix 阵列的 TCP 端口。默认值为 9440。 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认时间间隔为 60 分钟。 


| 性能轮询间隔（秒） | 性能轮询之间的间隔。默认值为 300 秒。 
|===


== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
