---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: 配置Dell EMC ScaleIO/PowerFlex数据收集器。 
---
= Dell EMC ScaleIO/PowerFlex数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
ScaleIO/PowerFlex数据收集器从ScaleIO和PowerFlex存储收集清单信息。在配置方面、此数据收集器需要ScaleIO/PowerFlex网关地址以及管理员用户名和密码。



== 术语

Data Infrastructure Insight从ScaleIO/PowerFlex数据收集器采集以下清单信息。对于Data Infrastructure Insight采集的每种资产类型、显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | 数据基础架构洞察力一词 


| MDM（ Meta Data Manager ）集群 | 存储 


| SDS (ScaleIO/PowerFlex数据服务器) | 存储节点 


| 存储池 | 存储池 


| 卷 | 卷 


| 设备 | 磁盘 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



== 要求

* 对管理员用户帐户的只读访问权限
* 端口要求： HTTPS 端口 443




== 配置

[cols="2*"]
|===
| 字段 | 说明 


| ScaleIO/PowerFlex网关 | ScaleIO/PowerFlex网关的IP地址或FQDN、以逗号(、)或分号(；)分隔 


| 用户名 | 用于登录到ScaleIO/PowerFlex设备的管理员用户名 


| 密码 | 用于登录到ScaleIO/PowerFlex设备的密码 
|===


== 高级配置

单击清单复选框以启用清单收集。

[cols="2*"]
|===
| 字段 | 说明 


| HTTPS端口 | 443 


| 清单轮询间隔（分钟） | 默认值为60。 


| 连接超时（秒） | 默认值为60。 
|===


== 故障排除

有关其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
