---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: 配置 IBM Cleversafe 数据收集器。 
---
= IBM Cleversafe 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights使用此数据收集器来发现 IBM Cleversafe 存储系统的库存和性能数据。


NOTE: IBM Cleversafe 按照不同的原始 TB 与托管单位费率进行计量。每 40 TB 未格式化的 IBM Cleversafe 容量按 1link:concept_subscribing_to_cloud_insights.html#pricing["管理单元（MU）"] 。



== Terminology

Data Infrastructure Insights从 IBM Cleversafe 数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 存储池 | 存储池 


| 容器 | 内部体积 


| 容器 | 文件共享 


| NFS 共享 | 共享 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

* 集群的外部数据服务 IP 地址
* 管理员用户名和密码
* 端口 9440




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| 管理器 IP 或主机名 | 管理节点的 IP 地址或主机名 


| 用户名 | 具有超级用户或系统管理员角色的用户帐户的用户名 


| 密码 | 具有超级用户或系统管理员角色的用户帐户的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。 


| HTTP 连接超时（秒） | HTTP 超时（秒）。 
|===


== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
