---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: 配置 DELL EMC Data Domain 数据收集器。 
---
= DELL EMC Data Domain 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
该数据收集器从 DELL EMC Data Domain 重复数据删除存储系统收集库存和性能信息。要配置此数据收集器，您必须遵循特定的配置说明和使用建议。



== Terminology

Data Infrastructure Insights从 Data Domain 数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| 磁盘 | 磁盘 


| 大批 | 存储 


| FC 端口 | 端口 


| 文件系统 | 内部体积 


| 配额 | 配额 


| NFS 和 CIFS 共享 | 文件共享 
|===
注意：这些只是常见的术语映射，可能并不代表该数据收集器的所有情况。



== 要求

您需要以下信息来配置此数据收集器：

* Data Domain 设备的 IP 地址
* Data Domain 存储的只读用户名和密码
* SSH 端口 22




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| IP 地址 | Data Domain 存储阵列的 IP 地址或完全限定域名 


| 用户名 | Data Domain 存储阵列的用户名 


| 密码 | Data Domain 存储阵列的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认值为 20。 


| SSH 端口 | SSH服务端口 
|===


== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
