---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: 配置 DELL EMC PowerStore 数据收集器。 
---
= Dell EMC PowerStore 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC PowerStore 数据收集器从 EMC PowerStore 存储收集库存信息。为了进行配置，数据收集器需要存储处理器的 IP 地址以及只读用户名和密码。

EMC PowerStore 数据收集器收集 PowerStore 在其他存储阵列之间协调的卷到卷的复制关系。Data Infrastructure Insights显示每个 PowerStore 集群的存储阵列，并收集该集群上的节点和存储端口的库存数据。未收集任何存储池或卷数据。



== Terminology

Data Infrastructure Insights从该数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| host | host 


| 主机卷映射 | 主机卷映射 


| 硬件（在“extra_details”对象下有驱动器）：驱动器 | 磁盘 


| 设备 | 存储池 


| 集群 | 存储阵列 


| 节点 | 存储节点 


| fc_端口 | 端口 


| volume | 卷 


| 内部容积 | 文件系统 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

配置此数据收集器需要以下信息：

* 存储处理器的 IP 地址或完全限定域名
* 只读用户名和密码




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| PowerStore 网关 | PowerStore 存储的 IP 地址或完全限定域名 


| 用户名 | PowerStore 的用户名 


| 密码 | PowerStore 使用的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| HTTPS 端口 | 默认值为 443 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认时间间隔为 60 分钟。 
|===
Cloud Insight 的 PowerStore 性能收集利用了 PowerStore 的 5 分钟粒度源数据。因此，Data Infrastructure Insights每五分钟轮询一次该数据，并且这是不可配置的。



== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
