---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: 配置 DELL EMC Celerra 数据收集器。 
---
= DELL EMC VNX File（以前称为 Celerra 统一存储系统）数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
该数据收集器从 VNX 文件存储系统获取库存信息。为了进行配置，此数据收集器需要存储处理器的 IP 地址以及只读用户名和密码。



== Terminology

Data Infrastructure Insights从 VNX 文件数据收集器获取以下库存信息。对于Data Infrastructure Insights获取的每种资产类型，都会显示用于该资产的最常用术语。查看或排除此数据收集器的故障时，请记住以下术语：

[cols="2*"]
|===
| 供应商/型号术语 | Data Infrastructure Insights术语 


| Celerra 网络服务器/Celerra 存储池 | 存储池 


| 文件系统 | 内部体积 


| 数据移动器 | 控制器 


| 安装在数据移动器上的文件系统 | 文件共享 


| CIFS 和 NFS 导出 | 共享 


| 磁盘卷 | 后端 LUN 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情况。



== 要求

您需要以下内容来配置此数据收集器：

* 存储处理器的 IP 地址
* 只读用户名和密码
* SSH 端口 22




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| VNX 文件 IP 地址 | VNX 文件设备的 IP 地址或完全限定域名 


| 用户名 | 用于登录 VNX File 设备的名称 


| 密码 | 用于登录 VNX File 设备的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认值为 20 分钟。 
|===


== 故障排除

如果您在使用此数据收集器时遇到问题，请尝试以下操作：



=== 清单

[cols="2*"]
|===
| 问题： | 尝试一下： 


| 错误：DART 更新正在进行中，无法继续 | 可能的解决方案：暂停数据收集器并等待 DART 升级完成后再尝试另一个采集请求。 
|===
更多信息可从link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
