---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: 配置 HDS 数据收集器。 
---
= Hitachi HCP 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此数据收集器使用 HCP 管理 API 支持 Hitachi 内容平台（ HCP ）。


NOTE: Hitachi内容平台按不同的原始TB到受管单元速率进行计量。每40 TB未格式化的HCP容量被充电为1link:concept_subscribing_to_cloud_insights.html#pricing["受管单元（ MU ）"]。



== 术语

Data Infrastructure Insight从Hitachi HCP数据收集器采集以下清单信息。对于Data Infrastructure Insight采集的每种资产类型、显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | 数据基础架构洞察力一词 


| HCP 集群 | 存储 


| 租户 | 存储池 


|  | 命名空间 


| 内部卷 | 节点 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



== 清单要求

要收集清单数据，您必须满足以下条件：

* HCP服务器的IP地址
* HCP 软件的只读用户名和密码以及对等权限




== 配置

[cols="2*"]
|===
| 字段 | 说明 


| HCP 主机 | HCP 主机的 IP 地址或完全限定域名 


| HCP端口 | 默认值为 9090 


| HCP 用户 ID | HCP 主机的用户名。 


| HCP密码 | 用于 HCP 主机的密码。 


| HCP 身份验证类型 | 选择 HCP_local 或 active_directory 
|===


== 高级配置

|===


| 字段 | 说明 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。默认值为60。 


| 性能轮询间隔（秒） | 性能轮询之间的时间间隔。默认值为900。 
|===
有关其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
