---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: 配置 Dell EMC Celerra 数据收集器。 
---
= Dell EMC VNX 文件（以前称为 Celerra 统一存储系统）数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
此数据收集器从 VNX 文件存储系统获取清单信息。在配置方面，此数据收集器需要存储处理器的 IP 地址以及只读用户名和密码。



== 术语

Data Infrastructure Insight从VNX文件数据收集器采集以下清单信息。对于Data Infrastructure Insight采集的每种资产类型、显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | 数据基础架构洞察力一词 


| Celerra 网络服务器 /Celerra 存储池 | 存储池 


| 文件系统 | 内部卷 


| 数据移动 | 控制器 


| 数据移动器上挂载的文件系统 | 文件共享 


| CIFS 和 NFS 导出 | 共享 


| 磁盘卷 | 后端 LUN 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



== 要求

要配置此数据收集器，您需要满足以下条件：

* 存储处理器的 IP 地址
* 只读用户名和密码
* SSH 端口 22




== 配置

[cols="2*"]
|===
| 字段 | 说明 


| VNX 文件 IP 地址 | VNX 文件设备的 IP 地址或完全限定域名 


| 用户名 | 用于登录到 VNX 文件设备的名称 


| 密码 | 用于登录到 VNX 文件设备的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。默认值为20分钟。 
|===


== 故障排除

如果此数据收集器出现问题，请尝试执行以下操作：



=== 清单

[cols="2*"]
|===
| 问题： | 请尝试以下操作： 


| 错误：在执行 DART 更新时无法继续 | 可能的解决方案：暂停数据收集器并等待 DART 升级完成，然后再尝试其他采集请求。 
|===
有关其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
