---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: 配置 NetApp SolidFire 数据收集器 
keywords: data collector, queries, create 
---
= NetApp SolidFire 全闪存阵列数据收集器
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp SolidFire 全闪存阵列数据收集器支持从 iSCSI 和光纤通道 SolidFire 配置收集清单和性能。

SolidFire 数据收集器利用 SolidFire REST API 。数据收集器所在的采集单元需要能够启动与 SolidFire 集群管理 IP 地址上的 TCP 端口 443 的 HTTPS 连接。数据收集器需要能够在 SolidFire 集群上进行 REST API 查询的凭据。



== 术语

数据基础架构洞察从NetApp SolidFire全闪存阵列数据收集器采集以下清单信息。对于Data Infrastructure Insight采集的每种资产类型、显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | 数据基础架构洞察力一词 


| 驱动器 | 磁盘 


| 集群 | 存储 


| 节点 | 存储节点 


| 卷 | 卷 


| 光纤通道端口 | 端口 


| 卷访问组， LUN 分配 | 卷映射 


| iSCSI 会话 | 卷掩码 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



== 要求

以下是配置此数据收集器的要求：

* 管理虚拟 IP 地址
* 只读用户名和凭据
* 端口 443




== 配置

[cols="2*"]
|===
| 字段 | 说明 


| 管理虚拟 IP 地址（ MVIP ） | SolidFire 集群的管理虚拟 IP 地址 


| 用户名 | 用于登录到 SolidFire 集群的名称 


| 密码 | 用于登录到 SolidFire 集群的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| 连接类型 | 选择连接类型 


| 通信端口 | 用于 NetApp API 的端口 


| 清单轮询间隔（分钟） | 默认值为 20 分钟 


| 性能轮询间隔（秒） | 默认值为300秒 
|===


== 故障排除

当SolidFire报告错误时、数据基础架构洞察会显示如下所示：

_尝试 检索数据时从 SolidFire 设备收到错误消息。此调用为 <method （ <parameterString> ）。来自设备的错误消息为（请查看设备手册）： <message>_

其中：

* method 是一种 HTTP 方法，例如 get 或 put 。
* parameterString> 是 REST 调用中包含的参数的逗号分隔列表。
* message> 是设备作为错误消息返回的内容。


有关此Data Collector的其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
