---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: 配置Azure NetApp Files数据收集器。 
---
= 配置Azure NetApp Files数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights使用Azure NetApp Files数据收集器来获取库存和性能数据。



== 要求

您需要以下信息来配置此数据收集器。

* 端口要求：443 HTTPS
* Azure 管理 Rest IP (management.azure.com)
* Azure 服务主体客户端 ID（用户帐户）
* Azure 服务主体身份验证密钥（用户密码）
* 您需要设置一个 Azure 帐户来发现Data Infrastructure Insights。
+
一旦正确配置了帐户并在 Azure 中注册了应用程序，您将拥有使用Data Infrastructure Insights发现 Azure 实例所需的凭据。以下链接描述了如何设置发现帐户：



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== 配置

根据下表将数据输入数据收集器字段：

[cols="2*"]
|===
| 字段 | 描述 


| Azure 服务主体客户端 ID | Azure 登录 ID 


| Azure 租户 ID | Azure 租户 ID 


| Azure 服务主体身份验证密钥 | 登录认证密钥 


| 我了解 Microsoft 会向我收取 API 请求费用 | 选中此项以验证您是否理解 Microsoft 会针对 Insight 轮询发出的 API 请求向您收费。 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| 库存轮询间隔（分钟） | 默认值为 60 
|===


== 故障排除

* ANF 数据收集器使用的凭据必须能够访问包含 ANF 卷的任何 Azure 订阅。
* 如果读者访问导致性能收集失败，请尝试在资源组级别授予贡献者访问权限。


关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
