---
sidebar: sidebar 
permalink: task_dc_aws_s3.html 
keywords: data collector, S3, Storage 
summary: 将AWS S3配置为存储数据收集器。 
---
= 将AWS S3配置为存储数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insight使用AWS S3作为存储数据收集器、从AWS S3实例获取清单和性能数据。



== 要求

要从AWS S3作为存储设备收集数据、您必须具有以下信息：

* 您必须具有以下项之一：
+
** AWS云帐户的* IAM角色*(如果使用IAM角色身份验证)。仅当采集单元安装在 AWS 实例上时， IAM 角色才适用。
** 如果使用IAM访问密钥身份验证、则为您的AWS云帐户提供* IAM访问密钥* ID和机密访问密钥。


* 您必须具有 " 列表组织 " 权限
* 端口443 HTTPS
* AWS S3实例可以报告为虚拟机、也可以报告为主机(不太自然)。EBS 卷既可以报告为虚拟机使用的虚拟磁盘，也可以报告为虚拟磁盘提供容量的数据存储库。


访问密钥由一个访问密钥 ID （例如， AKIIOSFODNN7EXAMPLE ）和一个机密访问密钥（例如， wJALRXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY ）组成。如果使用AWS SDK、REST或查询API操作、则可以使用访问密钥对向AWS发出的编程请求进行签名。这些密钥随 Amazon 的合同一起提供。



== 配置

根据下表在数据收集器字段中输入数据：

[cols="2*"]
|===
| 字段 | 说明 


| AWS 地区 | 选择 AWS 区域 


| IAM角色 | 仅在 AWS 中的 AU 上采集时使用。有关的详细信息，请参见下文<<iam-role,IAM角色>>。 


| AWS IAM 访问密钥 ID | 输入 AWS IAM 访问密钥 ID 。如果不使用 IAM 角色，则此为必填项。 


| AWS IAM 机密访问密钥 | 输入 AWS IAM 机密访问密钥。如果不使用 IAM 角色，则此为必填项。 


| 我了解 AWS 会向我发出 API 请求 | 选中此框可确认您已了解AWS会针对Data Infrastructure Insight轮询所发出的API请求向您收费。 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| 跨帐户角色 | 用于访问不同 AWS 帐户中的资源的角色。 


| 清单轮询间隔（分钟） | 默认值为60 


| 选择 " 排除 " 或 " 包括 " 以应用于按标记筛选 VM | 指定在收集数据时是包含还是排除虚拟机的按标记。如果选择了 ‘include ' ，则标记密钥字段不能为空。 


| 性能轮询间隔（秒） | 默认值为1800 
|===


== IAM访问密钥

访问密钥是 IAM 用户或 AWS 帐户 root 用户的长期凭据。访问密钥用于对指向 AWS 命令行界面或 AWS API 的编程请求进行签名（直接或使用 AWS SDK ）。

访问密钥包括两部分：访问密钥 ID 和机密访问密钥。使用 _IAM 访问密钥 _ 身份验证（与 _IAM 角色 _ 身份验证不同）时，必须同时使用访问密钥 ID 和机密访问密钥来对请求进行身份验证。有关详细信息，请参阅上的Amazon文档link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["访问密钥"]。



== IAM角色

使用 _IAM role_ 身份验证（与 IAM 访问密钥身份验证不同）时，您必须确保您创建或指定的角色具有访问资源所需的适当权限。

例如、如果您创建了一个名为_InstanceS3ReadOnly"的IAM角色、则必须设置此策略以为此IAM角色向所有S3资源授予S3只读列表访问权限。此外，您还必须授予 STS （安全令牌服务）访问权限，以便允许此角色跨帐户承担角色。

创建IAM角色后、您可以在创建新S3实例或任何现有S3实例时附加此角色。

将IAM角色_InstanceS3ReadOnly"附加到S3实例后、您将能够按IAM角色名称通过实例元数据检索临时凭据、并使用它通过此S3实例上运行的任何应用程序访问AWS资源。

有关详细信息，请参阅上的Amazon文档link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["IAM 角色"]。

注意：只有在采集单元在 AWS 实例中运行时，才能使用 IAM 角色。



== 将Amazon标记映射到Data Infrastructure Insight标注

作为存储数据收集器的AWS S3提供了一个选项、允许您使用在S3上配置的标记填充Data Infrastructure Insight标注。标注的名称必须与AWS标记完全相同。Data Infrastructure Insight将始终填充同名文本类型的标注、并"尽力"填充其他类型(数字、布尔值等)的标注。如果您的标注类型不同，而数据收集器无法填充，则可能需要删除此标注并将其重新创建为文本类型。

请注意、AWS区分大小写、而Data Infrastructure Insight不区分大小写。因此、如果您在Data Infrastructure Insight中创建名为"owner"的标注、并在S3中创建名为"owner"、"owner"和"owner"的标记、则所有S3变体"owner"都将映射到Cloud Insight的"owner"标注。



== 从 AWS 子帐户收集

Data Infrastructure Insight支持在一个AWS数据收集器中收集AWS的子帐户。此收集的配置在 AWS 环境中执行：

* 您必须将每个子帐户配置为具有一个AWS角色、此角色允许主帐户ID从子帐户访问S3详细信息。
* 每个子帐户都必须将角色名称配置为相同的字符串。
* 在Data Infrastructure Insight AWS Data Collector *高级配置*部分的*交叉帐户角色*字段中输入此角色名称字符串。
* 安装收集器的帐户需要具有_Delegate access administrator_ Privileges。link:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["AWS 文档"]有关详细信息、请参见。


最佳实践：强烈建议将AWS预定义的_AmazonS3ReadOnlyAccess_策略分配给S3主帐户。此外，在数据源中配置的用户应至少分配预定义的 _AWSOrganizationsReadOnlyAccess_ 策略，以便查询 AWS 。

有关配置您的环境以允许Data Infrastructure Insight从AWS子帐户收集数据的信息、请参见以下内容：

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["教程：使用 IAM 角色跨 AWS 帐户委派访问"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["AWS 设置：在您拥有的另一个 AWS 帐户中提供对 IAM 用户的访问权限"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["创建角色以将权限委派给 IAM 用户"]



== 故障排除

有关此Data Collector的其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
