---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: 配置 DELL EMC RecoverPoint 数据收集器。 
---
= Dell EMC RecoverPoint 数据收集器
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC RecoverPoint 数据收集器的主要用例是发现 RecoverPoint 存储设备所促进的卷到卷的复制关系。该收集器还将发现 Recoverpoint 设备本身。请注意，Dell/EMC 销售适用于虚拟机的 VMware 备份解决方案——“RecoverPoint for VMs”，但该收集器不支持该解决方案

为了进行配置，数据收集器需要存储处理器的 IP 地址以及只读用户名和密码。

EMC RecoverPoint 数据收集器收集 RecoverPoint 在其他存储阵列之间协调的卷到卷的复制关系。Data Infrastructure Insights显示每个 RecoverPoint 群集的存储阵列，并收集该群集上的节点和存储端口的库存数据。未收集任何存储池或卷数据。



== 要求

配置此数据收集器需要以下信息：

* 存储处理器的 IP 地址或完全限定域名
* 只读用户名和密码
* 通过端口 443 访问 REST API




== 配置

[cols="2*"]
|===
| 字段 | 描述 


| RecoverPoint 地址 | RecoverPoint 群集的 IP 地址或完全限定域名 


| 用户名 | RecoverPoint 群集的用户名 


| 密码 | RecoverPoint 群集使用的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 描述 


| TCP 端口 | 用于连接 Recoverpoint 群集的 TCP 端口 


| 库存轮询间隔（分钟） | 库存调查之间的间隔。默认值为 20 分钟。 


| 排除的集群 | 轮询时要排除的集群 ID 或名称的逗号分隔列表。 
|===


== 故障排除

关于此数据收集器的更多信息，请参阅link:concept_requesting_support.html["支持"]页面或在link:reference_data_collector_support_matrix.html["数据收集器支持矩阵"]。
