---
sidebar: sidebar 
permalink: task_dc_amazon_ec2.html 
keywords: data collector, EC2, 
summary: 配置 Amazon EC2 数据收集器。 
---
= 配置 Amazon EC2 数据收集器
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insight使用Amazon EC2数据收集器从EC2实例获取清单和性能数据。



== 要求

要从 Amazon EC2 设备收集数据，您必须具有以下信息：

* 您必须具有以下项之一：
+
** 如果使用 IAM 角色身份验证，则您的 Amazon EC2 云帐户的 * IAM 角色 * 。仅当采集单元安装在 AWS 实例上时， IAM 角色才适用。
** 如果使用 IAM 访问密钥身份验证，则为您的 Amazon EC2 云帐户提供 * IAM 访问密钥 * ID 和机密访问密钥。


* 您必须具有 " 列表组织 " 权限
* 端口443 HTTPS
* EC2 实例可以报告为虚拟机，也可以报告为主机（不太自然）。EBS 卷既可以报告为虚拟机使用的虚拟磁盘，也可以报告为虚拟磁盘提供容量的数据存储库。


访问密钥由一个访问密钥 ID （例如， AKIIOSFODNN7EXAMPLE ）和一个机密访问密钥（例如， wJALRXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY ）组成。如果您使用 Amazon EC2 SDK ， REST 或查询 API 操作，则可以使用访问密钥对向 EC2 发出的编程请求进行签名。这些密钥随 Amazon 的合同一起提供。



== 配置

根据下表在数据收集器字段中输入数据：

[cols="2*"]
|===
| 字段 | 说明 


| AWS 地区 | 选择 AWS 区域 


| IAM角色 | 仅在 AWS 中的 AU 上采集时使用。有关的详细信息，请参见下文<<iam-role,IAM角色>>。 


| AWS IAM 访问密钥 ID | 输入 AWS IAM 访问密钥 ID 。如果不使用 IAM 角色，则此为必填项。 


| AWS IAM 机密访问密钥 | 输入 AWS IAM 机密访问密钥。如果不使用 IAM 角色，则此为必填项。 


| 我了解 AWS 会向我发出 API 请求 | 选中此框可确认您已了解AWS会针对Data Infrastructure Insight轮询所发出的API请求向您收费。 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| 包括其他区域 | 指定要包括在轮询中的其他区域。 


| 跨帐户角色 | 用于访问不同 AWS 帐户中的资源的角色。 


| 清单轮询间隔（分钟） | 默认值为60 


| 选择 " 排除 " 或 " 包括 " 以应用于按标记筛选 VM | 指定在收集数据时是包含还是排除虚拟机的按标记。如果选择了 ‘include ' ，则标记密钥字段不能为空。 


| 标记要筛选 VM 的密钥和值 | 单击 * + Filter Tag * ，通过筛选与 VM 上的密钥和标记值匹配的密钥和值来选择要包含 / 排除的 VM （以及关联磁盘）。标记密钥为必填项，标记值为可选项。如果标记值为空，则只要虚拟机与标记密钥匹配，就会对其进行筛选。 


| 性能轮询间隔（秒） | 默认值为1800 


| CloudWatch 代理指标命名空间 | EC2/EBS 中用于收集数据的命名空间。请注意、如果更改此命名空间中默认度量指标的名称、Data Infrastructure Insight可能无法收集重命名后的数据。建议保留默认指标名称。 
|===


== IAM访问密钥

访问密钥是 IAM 用户或 AWS 帐户 root 用户的长期凭据。访问密钥用于对指向 AWS 命令行界面或 AWS API 的编程请求进行签名（直接或使用 AWS SDK ）。

访问密钥包括两部分：访问密钥 ID 和机密访问密钥。使用 _IAM 访问密钥 _ 身份验证（与 _IAM 角色 _ 身份验证不同）时，必须同时使用访问密钥 ID 和机密访问密钥来对请求进行身份验证。有关详细信息，请参阅上的Amazon文档link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["访问密钥"]。



== IAM角色

使用 _IAM role_ 身份验证（与 IAM 访问密钥身份验证不同）时，您必须确保您创建或指定的角色具有访问资源所需的适当权限。

例如，如果您创建了一个名为 _InstanceEE2ReadOnly" 的 IAM 角色，则必须设置此策略，以便为此 IAM 角色向所有 EC2 资源授予 EC2 只读列表访问权限。此外，您还必须授予 STS （安全令牌服务）访问权限，以便允许此角色跨帐户承担角色。

创建IAM角色后、您可以在创建新EC2实例或任何现有EC2实例时附加此角色。

将 IAM 角色 _InstanceEE2ReadOnly" 附加到 EC2 实例后，您将能够通过实例元数据按 IAM 角色名称检索临时凭据，并使用它通过在此 EC2 实例上运行的任何应用程序访问 AWS 资源。

有关详细信息，请参阅上的Amazon文档link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["IAM 角色"]。

注意：只有在采集单元在 AWS 实例中运行时，才能使用 IAM 角色。



== 将Amazon标记映射到Data Infrastructure Insight标注

Amazon EC2数据收集器提供了一个选项、可用于使用EC2上配置的标记填充Data Infrastructure Insight标注。标注的名称必须与 EC2 标记完全相同。Data Infrastructure Insight将始终填充同名文本类型的标注、并"尽力"填充其他类型(数字、布尔值等)的标注。如果您的标注类型不同，而数据收集器无法填充，则可能需要删除此标注并将其重新创建为文本类型。

请注意、AWS区分大小写、而Data Infrastructure Insight不区分大小写。因此、如果您在Data Infrastructure Insight中创建了一个名为"owner"的标注、并在EC2中创建了名为"owner"、"owner"和"owner"的标记、则所有EC2变体"owner"都将映射到Cloud Insight的"owner"标注。



== 包括其他区域

在 AWS Data Collector * 高级配置 * 部分中，您可以设置 * 包括额外区域 * 字段以包括其他区域，以逗号或分号分隔。默认情况下，此字段设置为 * 。 * _ * ，它会在所有美国 AWS 地区收集数据。要在 _all_ 地区收集数据，请将此字段设置为 * 。 * _ * 。如果 * 包括额外区域 * 字段为空，则数据收集器将收集在 * 配置 * 部分中指定的 * AWS 区域 * 字段中指定的资产。



== 从 AWS 子帐户收集

Data Infrastructure Insight支持在一个AWS数据收集器中收集AWS的子帐户。此收集的配置在 AWS 环境中执行：

* 您必须将每个子帐户配置为具有一个AWS角色、此角色允许主帐户ID从子帐户访问EC2详细信息。
* 每个子帐户都必须将角色名称配置为相同的字符串。
* 在Data Infrastructure Insight AWS Data Collector *高级配置*部分的*交叉帐户角色*字段中输入此角色名称字符串。
* 安装收集器的帐户需要具有_Delegate access administrator_ Privileges。link:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["AWS 文档"]有关详细信息、请参见。


最佳实践：强烈建议将 AWS 预定义的 _AmazonEC2ReadOnlyAccess_ 策略分配给 EC2 主帐户。此外，在数据源中配置的用户应至少分配预定义的 _AWSOrganizationsReadOnlyAccess_ 策略，以便查询 AWS 。

有关配置您的环境以允许Data Infrastructure Insight从AWS子帐户收集数据的信息、请参见以下内容：

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["教程：使用 IAM 角色跨 AWS 帐户委派访问"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["AWS 设置：在您拥有的另一个 AWS 帐户中提供对 IAM 用户的访问权限"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["创建角色以将权限委派给 IAM 用户"]



== 故障排除

有关此Data Collector的其他信息，请参见link:concept_requesting_support.html["支持"]页面或link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
